import type { Book } from "@/types/book"

// Mock data for books with social stats
export const books: Book[] = [
  {
    id: "moby-dick",
    title: "Moby Dick",
    author: "Herman Melville",
    description: "The epic tale of Captain Ahab's obsessive quest to kill the white whale, Moby Dick.",
    coverUrl: "/book-covers/moby-dick.png",
    genres: ["Classics", "Adventure", "Sea Story"],
    duration: "24h",
    pages: 635,
    category: "classics",
    listeners: 23410,
    rating: 4.3,
    reviewCount: 5432,
    peopleReading: 1247,
    comments: 892,
    loves: 2156,
    chapters: [
      { id: "ch-1", title: "Loomings", duration: "45m", audioUrl: "/audio/moby-dick/ch-1.mp3" },
      { id: "ch-2", title: "The Carpet-Bag", duration: "40m", audioUrl: "/audio/moby-dick/ch-2.mp3" },
      { id: "ch-4", title: "The Counterpane", duration: "38m", audioUrl: "/audio/moby-dick/ch-4.mp3" },
      { id: "ch-5", title: "Breakfast", duration: "35m", audioUrl: "/audio/moby-dick/ch-5.mp3" },
    ],
  },
  {
    id: "pride-and-prejudice",
    title: "Pride and Prejudice",
    author: "Jane Austen",
    description: "Pride and Prejudice follows the turbulent relationship between Elizabeth Bennet and Fitzwilliam Darcy.",
    coverUrl: "/book-covers/pride-and-prejudice.png",
    genres: ["Classics", "Romance", "Fiction"],
    duration: "11h",
    pages: 432,
    category: "classics",
    listeners: 45620,
    rating: 4.8,
    reviewCount: 8923,
    peopleReading: 3421,
    comments: 2156,
    loves: 5678,
    chapters: [
      { id: "ch-1", title: "Chapter 1", duration: "15m", audioUrl: "/audio/pride-and-prejudice/ch-1.mp3" },
      { id: "ch-2", title: "Chapter 2", duration: "18m", audioUrl: "/audio/pride-and-prejudice/ch-2.mp3" },
      { id: "ch-4", title: "Chapter 4", duration: "17m", audioUrl: "/audio/pride-and-prejudice/ch-4.mp3" },
    ],
  },
  {
    id: "the-great-gatsby",
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    description: "Set in the Jazz Age on Long Island, the novel depicts narrator Nick Carraway's interactions with mysterious millionaire Jay Gatsby.",
    coverUrl: "/book-covers/the-great-gatsby.png",
    genres: ["Classics", "Fiction", "Literary"],
    duration: "5h",
    pages: 180,
    category: "classics",
    listeners: 38945,
    rating: 4.6,
    reviewCount: 7654,
    peopleReading: 2891,
    comments: 1876,
    loves: 4234,
    chapters: [
      { id: "ch-1", title: "Chapter 1", duration: "25m", audioUrl: "/audio/great-gatsby/ch-1.mp3" },
      { id: "ch-2", title: "Chapter 2", duration: "22m", audioUrl: "/audio/great-gatsby/ch-2.mp3" },
      { id: "ch-3", title: "Chapter 3", duration: "28m", audioUrl: "/audio/great-gatsby/ch-3.mp3" },
      { id: "ch-4", title: "Chapter 4", duration: "24m", audioUrl: "/audio/great-gatsby/ch-4.mp3" },
      { id: "ch-5", title: "Chapter 5", duration: "26m", audioUrl: "/audio/great-gatsby/ch-5.mp3" },
    ],
  },
  {
    id: "to-kill-a-mockingbird",
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    description: "A powerful story of racial injustice and the loss of innocence in the American South.",
    coverUrl: "/book-covers/to-kill-a-mockingbird.png",
    genres: ["Classics", "Fiction", "Social Issues"],
    duration: "6h 30m",
    pages: 281,
    category: "classics",
    listeners: 30000,
    rating: 4.9,
    reviewCount: 6000,
    peopleReading: 2156,
    comments: 1342,
    loves: 3891,
    chapters: [
      { id: "ch-1", title: "Part One: Chapter 1", duration: "30m", audioUrl: "/audio/to-kill-a-mockingbird/ch-1.mp3" },
      { id: "ch-3", title: "Part One: Chapter 3", duration: "32m", audioUrl: "/audio/to-kill-a-mockingbird/ch-3.mp3" },
      { id: "ch-5", title: "Part One: Chapter 5", duration: "29m", audioUrl: "/audio/to-kill-a-mockingbird/ch-5.mp3" },
    ],
  },
  {
    id: "jane-eyre",
    title: "Jane Eyre",
    author: "Charlotte Brontë",
    description: "Jane Eyre follows the experiences of its eponymous heroine, including her growth to adulthood and her love for Mr. Rochester.",
    coverUrl: "/book-covers/jane-eyre.png",
    genres: ["Classics", "Romance", "Gothic"],
    duration: "15h",
    pages: 624,
    category: "classics",
    listeners: 25000,
    rating: 4.7,
    reviewCount: 4500,
    peopleReading: 1800,
    comments: 1100,
    loves: 3200,
    chapters: [
      { id: "ch-1", title: "Chapter 1", duration: "45m", audioUrl: "/audio/jane-eyre/ch-1.mp3" },
      { id: "ch-2", title: "Chapter 2", duration: "42m", audioUrl: "/audio/jane-eyre/ch-2.mp3" },
      { id: "ch-3", title: "Chapter 3", duration: "48m", audioUrl: "/audio/jane-eyre/ch-3.mp3" },
      { id: "ch-4", title: "Chapter 4", duration: "40m", audioUrl: "/audio/jane-eyre/ch-4.mp3" },
      { id: "ch-5", title: "Chapter 5", duration: "44m", audioUrl: "/audio/jane-eyre/ch-5.mp3" },
    ],
  },
  {
    id: "wuthering-heights",
    title: "Wuthering Heights",
    author: "Emily Brontë",
    description: "A tale of love, revenge, and the destructive power of passion set against the backdrop of the Yorkshire moors.",
    coverUrl: "/book-covers/wuthering-heights.png",
    genres: ["Classics", "Romance", "Gothic"],
    duration: "12h",
    pages: 464,
    category: "classics",
    listeners: 22000,
    rating: 4.5,
    reviewCount: 3800,
    peopleReading: 1600,
    comments: 950,
    loves: 2800,
    chapters: [
      { id: "ch-3", title: "Chapter 3", duration: "30m", audioUrl: "/audio/wuthering-heights/ch-3.mp3" },
      { id: "ch-4", title: "Chapter 4", duration: "32m", audioUrl: "/audio/wuthering-heights/ch-4.mp3" },
    ],
  },
  {
    id: "crime-and-punishment",
    title: "Crime and Punishment",
    author: "Fyodor Dostoevsky",
    description: "A psychological thriller exploring the moral dilemmas of a young man who commits murder.",
    coverUrl: "/book-covers/crime-and-punishment.png",
    genres: ["Classics", "Psychological", "Literary"],
    duration: "18h",
    pages: 671,
    category: "classics",
    listeners: 18000,
    rating: 4.6,
    reviewCount: 3200,
    peopleReading: 1200,
    comments: 750,
    loves: 2100,
    chapters: [
      { id: "ch-1", title: "Part 1, Chapter 1", duration: "45m", audioUrl: "/audio/crime-and-punishment/ch-1.mp3" },
      { id: "ch-2", title: "Part 1, Chapter 2", duration: "42m", audioUrl: "/audio/crime-and-punishment/ch-2.mp3" },
      { id: "ch-3", title: "Part 1, Chapter 3", duration: "48m", audioUrl: "/audio/crime-and-punishment/ch-3.mp3" },
      { id: "ch-4", title: "Part 1, Chapter 4", duration: "40m", audioUrl: "/audio/crime-and-punishment/ch-4.mp3" },
      { id: "ch-5", title: "Part 1, Chapter 5", duration: "44m", audioUrl: "/audio/crime-and-punishment/ch-5.mp3" },
    ],
  },
  {
    id: "anna-karenina",
    title: "Anna Karenina",
    author: "Leo Tolstoy",
    description: "A tragic love story set against the backdrop of Russian high society.",
    coverUrl: "/book-covers/anna-karenina.png",
    genres: ["Classics", "Romance", "Literary"],
    duration: "20h",
    pages: 864,
    category: "classics",
    listeners: 15000,
    rating: 4.7,
    reviewCount: 2800,
    peopleReading: 1000,
    comments: 600,
    loves: 1800,
    chapters: [
      { id: "ch-3", title: "Part 1, Chapter 3", duration: "20m", audioUrl: "/audio/anna-karenina/ch-3.mp3" },
      { id: "ch-4", title: "Part 1, Chapter 4", duration: "19m", audioUrl: "/audio/anna-karenina/ch-4.mp3" },
      { id: "ch-5", title: "Part 1, Chapter 5", duration: "22m", audioUrl: "/audio/anna-karenina/ch-5.mp3" },
    ],
  },
  {
    id: "the-time-machine",
    title: "The Time Machine",
    author: "H.G. Wells",
    description: "A Victorian scientist travels to the future and discovers a world divided between the Eloi and the Morlocks.",
    coverUrl: "/book-covers/the-time-machine.png",
    genres: ["Sci-Fi", "Classics", "Adventure"],
    duration: "3h",
    pages: 118,
    category: "sci-fi",
    listeners: 28000,
    rating: 4.4,
    reviewCount: 5200,
    peopleReading: 2100,
    comments: 1200,
    loves: 3500,
    chapters: [
      { id: "ch-1", title: "Introduction", duration: "15m", audioUrl: "/audio/time-machine/ch-1.mp3" },
      { id: "ch-2", title: "The Machine", duration: "20m", audioUrl: "/audio/time-machine/ch-2.mp3" },
      { id: "ch-5", title: "The Morlocks", duration: "35m", audioUrl: "/audio/time-machine/ch-5.mp3" },
    ],
  },
  {
    id: "don-quixote",
    title: "Don Quixote",
    author: "Miguel de Cervantes",
    description: "The adventures of a delusional knight and his loyal squire in 17th century Spain.",
    coverUrl: "/book-covers/don-quixote.png",
    genres: ["Classics", "Adventure", "Humor"],
    duration: "25h",
    pages: 863,
    category: "classics",
    listeners: 12000,
    rating: 4.3,
    reviewCount: 2200,
    peopleReading: 800,
    comments: 450,
    loves: 1300,
    chapters: [
      { id: "ch-2", title: "Part 1, Chapter 2", duration: "28m", audioUrl: "/audio/don-quixote/ch-2.mp3" },
      { id: "ch-4", title: "Part 1, Chapter 4", duration: "24m", audioUrl: "/audio/don-quixote/ch-4.mp3" },
    ],
  },
  {
    id: "the-divine-comedy",
    title: "The Divine Comedy",
    author: "Dante Alighieri",
    description: "An epic poem describing Dante's journey through Hell, Purgatory, and Paradise.",
    coverUrl: "/book-covers/the-divine-comedy.png",
    genres: ["Classics", "Poetry", "Religious"],
    duration: "16h",
    pages: 798,
    category: "classics",
    listeners: 10000,
    rating: 4.5,
    reviewCount: 1800,
    peopleReading: 600,
    comments: 300,
    loves: 900,
    chapters: [
      { id: "ch-1", title: "Inferno, Canto I", duration: "15m", audioUrl: "/audio/divine-comedy/ch-1.mp3" },
      { id: "ch-2", title: "Inferno, Canto II", duration: "18m", audioUrl: "/audio/divine-comedy/ch-2.mp3" },
      { id: "ch-4", title: "Inferno, Canto IV", duration: "17m", audioUrl: "/audio/divine-comedy/ch-4.mp3" },
    ],
  },
  {
    id: "frankenstein",
    title: "Frankenstein",
    author: "Mary Shelley",
    description: "A young scientist creates a monster in an unorthodox scientific experiment.",
    coverUrl: "/book-covers/frankenstein.png",
    genres: ["Sci-Fi", "Gothic", "Horror"],
    duration: "8h",
    pages: 280,
    category: "sci-fi",
    listeners: 35000,
    rating: 4.6,
    reviewCount: 6800,
    peopleReading: 2600,
    comments: 1500,
    loves: 4200,
    chapters: [
      { id: "ch-1", title: "Chapter 1", duration: "30m", audioUrl: "/audio/frankenstein/ch-1.mp3" },
      { id: "ch-2", title: "Chapter 2", duration: "28m", audioUrl: "/audio/frankenstein/ch-2.mp3" },
      { id: "ch-3", title: "Chapter 3", duration: "32m", audioUrl: "/audio/frankenstein/ch-3.mp3" },
    ],
  },
  {
    id: "dracula",
    title: "Dracula",
    author: "Bram Stoker",
    description: "The classic vampire tale of Count Dracula's attempt to move from Transylvania to England.",
    coverUrl: "/book-covers/dracula.png",
    genres: ["Horror", "Gothic", "Classics"],
    duration: "10h",
    pages: 418,
    category: "horror",
    listeners: 32000,
    rating: 4.5,
    reviewCount: 5800,
    peopleReading: 2400,
    comments: 1300,
    loves: 3800,
    chapters: [
      { id: "ch-1", title: "Chapter 1", duration: "25m", audioUrl: "/audio/dracula/ch-1.mp3" },
      { id: "ch-2", title: "Chapter 2", duration: "28m", audioUrl: "/audio/dracula/ch-2.mp3" },
      { id: "ch-3", title: "Chapter 3", duration: "30m", audioUrl: "/audio/dracula/ch-3.mp3" },
    ],
  },
  {
    id: "the-secret-garden",
    title: "The Secret Garden",
    author: "Frances Hodgson Burnett",
    description: "A young girl discovers a magical garden that changes her life and those around her.",
    coverUrl: "/book-covers/the-secret-garden.png",
    genres: ["Children", "Classics", "Fantasy"],
    duration: "6h",
    pages: 288,
    category: "children",
    listeners: 25000,
    rating: 4.7,
    reviewCount: 4200,
    peopleReading: 1800,
    comments: 900,
    loves: 2800,
    chapters: [
      { id: "ch-1", title: "Chapter 1", duration: "20m", audioUrl: "/audio/secret-garden/ch-1.mp3" },
      { id: "ch-2", title: "Chapter 2", duration: "22m", audioUrl: "/audio/secret-garden/ch-2.mp3" },
      { id: "ch-3", title: "Chapter 3", duration: "25m", audioUrl: "/audio/secret-garden/ch-3.mp3" },
    ],
  },
  {
    id: "peter-pan",
    title: "Peter Pan",
    author: "J.M. Barrie",
    description: "The magical story of a boy who never grows up and his adventures in Neverland.",
    coverUrl: "/book-covers/peter-pan.png",
    genres: ["Fantasy", "Children", "Adventure"],
    duration: "4h",
    pages: 192,
    category: "children",
    listeners: 30000,
    rating: 4.8,
    reviewCount: 5500,
    peopleReading: 2200,
    comments: 1200,
    loves: 3600,
    chapters: [
      { id: "ch-1", title: "Chapter 1", duration: "18m", audioUrl: "/audio/peter-pan/ch-1.mp3" },
      { id: "ch-2", title: "Chapter 2", duration: "20m", audioUrl: "/audio/peter-pan/ch-2.mp3" },
      { id: "ch-3", title: "Chapter 3", duration: "22m", audioUrl: "/audio/peter-pan/ch-3.mp3" },
    ],
  },
  {
    id: "alice-in-wonderland",
    title: "Alice's Adventures in Wonderland",
    author: "Lewis Carroll",
    description: "A young girl falls down a rabbit hole into a world of fantasy and nonsense.",
    coverUrl: "/book-covers/alice-in-wonderland.png",
    genres: ["Fantasy", "Children", "Classics"],
    duration: "3h",
    pages: 96,
    category: "children",
    listeners: 35000,
    rating: 4.6,
    reviewCount: 6200,
    peopleReading: 2800,
    comments: 1500,
    loves: 4200,
    chapters: [
      { id: "ch-1", title: "Down the Rabbit-Hole", duration: "15m", audioUrl: "/audio/alice/ch-1.mp3" },
      { id: "ch-2", title: "The Pool of Tears", duration: "18m", audioUrl: "/audio/alice/ch-2.mp3" },
      { id: "ch-3", title: "A Caucus-Race and a Long Tale", duration: "20m", audioUrl: "/audio/alice/ch-3.mp3" },
    ],
  },
  {
    id: "stand-on-zanzibar",
    title: "Stand on Zanzibar",
    author: "John Brunner",
    description: "A dystopian novel set in an overpopulated world of 2010.",
    coverUrl: "/book-covers/amz-stand-on-zanzibar.jpg",
    genres: ["Sci-Fi", "Dystopian", "Modern"],
    duration: "12h",
    pages: 576,
    category: "sci-fi",
    listeners: 8000,
    rating: 4.2,
    reviewCount: 1200,
    peopleReading: 500,
    comments: 250,
    loves: 800,
    chapters: [
      { id: "ch-1", title: "Chapter 1", duration: "30m", audioUrl: "/audio/stand-on-zanzibar/ch-1.mp3" },
      { id: "ch-2", title: "Chapter 2", duration: "28m", audioUrl: "/audio/stand-on-zanzibar/ch-2.mp3" },
      { id: "ch-3", title: "Chapter 3", duration: "32m", audioUrl: "/audio/stand-on-zanzibar/ch-3.mp3" },
    ],
  },
  {
    id: "dhalgren",
    title: "Dhalgren",
    author: "Samuel R. Delany",
    description: "An experimental science fiction novel set in a mysterious city.",
    coverUrl: "/book-covers/amz-dhalgren.jpg",
    genres: ["Experimental", "Sci-Fi", "Literary"],
    duration: "20h",
    pages: 801,
    category: "sci-fi",
    listeners: 5000,
    rating: 4.0,
    reviewCount: 800,
    peopleReading: 300,
    comments: 150,
    loves: 500,
    chapters: [
      { id: "ch-1", title: "Chapter 1", duration: "45m", audioUrl: "/audio/dhalgren/ch-1.mp3" },
      { id: "ch-2", title: "Chapter 2", duration: "42m", audioUrl: "/audio/dhalgren/ch-2.mp3" },
      { id: "ch-3", title: "Chapter 3", duration: "48m", audioUrl: "/audio/dhalgren/ch-3.mp3" },
    ],
  },
  {
    id: "a-walk-in-the-woods",
    title: "A Walk in the Woods",
    author: "Bill Bryson",
    description: "A humorous account of hiking the Appalachian Trail.",
    coverUrl: "/book-covers/a-walk-in-the-woods.png",
    genres: ["Non-Fiction", "Adventure", "Nature"],
    duration: "8h",
    pages: 304,
    category: "non-fiction",
    listeners: 18000,
    rating: 4.4,
    reviewCount: 3200,
    peopleReading: 1400,
    comments: 700,
    loves: 2100,
    chapters: [
      { id: "ch-1", title: "Chapter 1", duration: "25m", audioUrl: "/audio/walk-in-woods/ch-1.mp3" },
      { id: "ch-2", title: "Chapter 2", duration: "28m", audioUrl: "/audio/walk-in-woods/ch-2.mp3" },
      { id: "ch-3", title: "Chapter 3", duration: "30m", audioUrl: "/audio/walk-in-woods/ch-3.mp3" },
    ],
  },
  {
    id: "morning-glory",
    title: "Morning Glory",
    author: "LaVyrle Spencer",
    description: "A romance novel about finding love in unexpected places.",
    coverUrl: "/book-covers/morning-glory.png",
    genres: ["Romance", "Contemporary"],
    duration: "6h",
    pages: 384,
    category: "romance",
    listeners: 12000,
    rating: 4.3,
    reviewCount: 1800,
    peopleReading: 800,
    comments: 400,
    loves: 1200,
    chapters: [
      { id: "ch-1", title: "Chapter 1", duration: "20m", audioUrl: "/audio/morning-glory/ch-1.mp3" },
      { id: "ch-2", title: "Chapter 2", duration: "22m", audioUrl: "/audio/morning-glory/ch-2.mp3" },
      { id: "ch-3", title: "Chapter 3", duration: "25m", audioUrl: "/audio/morning-glory/ch-3.mp3" },
    ],
  },
  {
    id: "the-last-policeman",
    title: "The Last Policeman",
    author: "Ben H. Winters",
    description: "A detective novel set in a world facing an impending asteroid collision.",
    coverUrl: "/book-covers/amz-the-last-policeman.jpg",
    genres: ["Mystery", "Dystopian", "Contemporary"],
    duration: "7h",
    pages: 336,
    category: "mystery",
    listeners: 15000,
    rating: 4.5,
    reviewCount: 2500,
    peopleReading: 1000,
    comments: 500,
    loves: 1500,
    chapters: [
      { id: "ch-1", title: "Chapter 1", duration: "22m", audioUrl: "/audio/last-policeman/ch-1.mp3" },
      { id: "ch-2", title: "Chapter 2", duration: "25m", audioUrl: "/audio/last-policeman/ch-2.mp3" },
      { id: "ch-3", title: "Chapter 3", duration: "28m", audioUrl: "/audio/last-policeman/ch-3.mp3" },
    ],
  },
  {
    id: "bag-of-bones",
    title: "Bag of Bones",
    author: "Stephen King",
    description: "A supernatural thriller about a writer haunted by ghosts and dark secrets.",
    coverUrl: "/book-covers/bag-of-bones.png",
    genres: ["Horror", "Supernatural", "Thriller"],
    duration: "14h",
    pages: 529,
    category: "horror",
    listeners: 22000,
    rating: 4.4,
    reviewCount: 3800,
    peopleReading: 1600,
    comments: 800,
    loves: 2400,
    chapters: [
      { id: "ch-1", title: "Chapter 1", duration: "30m", audioUrl: "/audio/bag-of-bones/ch-1.mp3" },
      { id: "ch-2", title: "Chapter 2", duration: "32m", audioUrl: "/audio/bag-of-bones/ch-2.mp3" },
      { id: "ch-3", title: "Chapter 3", duration: "35m", audioUrl: "/audio/bag-of-bones/ch-3.mp3" },
    ],
  },
  {
    id: "the-sparrow",
    title: "The Sparrow",
    author: "Mary Doria Russell",
    description: "A science fiction novel about first contact with an alien civilization.",
    coverUrl: "/book-covers/amz-the-sparrow.jpg",
    genres: ["Sci-Fi", "Religious", "Philosophical"],
    duration: "11h",
    pages: 408,
    category: "sci-fi",
    listeners: 10000,
    rating: 4.6,
    reviewCount: 1800,
    peopleReading: 700,
    comments: 350,
    loves: 1100,
    chapters: [
      { id: "ch-1", title: "Chapter 1", duration: "28m", audioUrl: "/audio/sparrow/ch-1.mp3" },
      { id: "ch-2", title: "Chapter 2", duration: "30m", audioUrl: "/audio/sparrow/ch-2.mp3" },
      { id: "ch-3", title: "Chapter 3", duration: "32m", audioUrl: "/audio/sparrow/ch-3.mp3" },
    ],
  },
  {
    id: "the-right-stuff",
    title: "The Right Stuff",
    author: "Tom Wolfe",
    description: "A non-fiction account of the early days of the U.S. space program.",
    coverUrl: "/book-covers/amz-the-right-stuff.jpg",
    genres: ["Non-Fiction", "History", "Space"],
    duration: "10h",
    pages: 448,
    category: "non-fiction",
    listeners: 14000,
    rating: 4.5,
    reviewCount: 2200,
    peopleReading: 900,
    comments: 450,
    loves: 1300,
    chapters: [
      { id: "ch-1", title: "Chapter 1", duration: "25m", audioUrl: "/audio/right-stuff/ch-1.mp3" },
      { id: "ch-2", title: "Chapter 2", duration: "28m", audioUrl: "/audio/right-stuff/ch-2.mp3" },
      { id: "ch-3", title: "Chapter 3", duration: "30m", audioUrl: "/audio/right-stuff/ch-3.mp3" },
    ],
  },
  {
    id: "bet-me",
    title: "Bet Me",
    author: "Jennifer Crusie",
    description: "A contemporary romance about a bet that leads to unexpected love.",
    coverUrl: "/book-covers/bet-me.png",
    genres: ["Romance", "Contemporary", "Humor"],
    duration: "8h",
    pages: 384,
    category: "romance",
    listeners: 16000,
    rating: 4.3,
    reviewCount: 2400,
    peopleReading: 1000,
    comments: 500,
    loves: 1500,
    chapters: [
      { id: "ch-1", title: "Chapter 1", duration: "22m", audioUrl: "/audio/bet-me/ch-1.mp3" },
      { id: "ch-2", title: "Chapter 2", duration: "25m", audioUrl: "/audio/bet-me/ch-2.mp3" },
      { id: "ch-3", title: "Chapter 3", duration: "28m", audioUrl: "/audio/bet-me/ch-3.mp3" },
    ],
  },
  {
    id: "the-brethren",
    title: "The Brethren",
    author: "John Grisham",
    description: "A legal thriller about three former judges serving time in prison.",
    coverUrl: "/book-covers/amz-the-breatheren.jpg",
    genres: ["Legal", "Thriller", "Contemporary"],
    duration: "9h",
    pages: 384,
    category: "thriller",
    listeners: 20000,
    rating: 4.4,
    reviewCount: 3200,
    peopleReading: 1200,
    comments: 600,
    loves: 1800,
    chapters: [
      { id: "ch-1", title: "Chapter 1", duration: "24m", audioUrl: "/audio/brethren/ch-1.mp3" },
      { id: "ch-2", title: "Chapter 2", duration: "26m", audioUrl: "/audio/brethren/ch-2.mp3" },
      { id: "ch-3", title: "Chapter 3", duration: "28m", audioUrl: "/audio/brethren/ch-3.mp3" },
    ],
  },
  {
    id: "call-of-the-wild",
    title: "The Call of the Wild",
    author: "Jack London",
    description: "A dog's journey from domestication to wildness in the Yukon during the Klondike Gold Rush.",
    coverUrl: "/book-covers/the-call-of-the-wild.png",
    genres: ["Adventure", "Classics", "Nature"],
    duration: "4h",
    pages: 172,
    category: "adventure",
    listeners: 25000,
    rating: 4.6,
    reviewCount: 4200,
    peopleReading: 1800,
    comments: 900,
    loves: 2800,
    chapters: [
      { id: "1", title: "Chapter 1", duration: "45m", audioUrl: "/audio/call-of-the-wild/chapter1.mp3" },
      { id: "3", title: "Chapter 3", duration: "42m", audioUrl: "/audio/call-of-the-wild/chapter3.mp3" },
      { id: "4", title: "Chapter 4", duration: "40m", audioUrl: "/audio/call-of-the-wild/chapter4.mp3" },
    ],
  },
  {
    id: "a-room-with-a-view",
    title: "A Room with a View",
    author: "E.M. Forster",
    description: "A young woman's journey of self-discovery and love in Edwardian England.",
    coverUrl: "/book-covers/a-room-with-a-view.png",
    genres: ["Classics", "Romance", "Literary"],
    duration: "6h",
    pages: 240,
    category: "classics",
    listeners: 18000,
    rating: 4.5,
    reviewCount: 2800,
    peopleReading: 1200,
    comments: 600,
    loves: 1800,
    chapters: [
      { id: "ch-1", title: "Chapter 1", duration: "20m", audioUrl: "/audio/room-with-view/ch-1.mp3" },
      { id: "ch-2", title: "Chapter 2", duration: "22m", audioUrl: "/audio/room-with-view/ch-2.mp3" },
      { id: "ch-3", title: "Chapter 3", duration: "25m", audioUrl: "/audio/room-with-view/ch-3.mp3" },
    ],
  }
];

// Helper functions
export function getAllBooks(): Book[] {
  return books;
}

export function getBookById(id: string): Book | undefined {
  return books.find(book => book.id === id);
}

export function getSocialFeedBooks(): Book[] {
  // Return books with social engagement data
  return books.filter(book => book.peopleReading > 0);
}

export function getCurrentBook(): Book | null {
  // In a real app, this would get the currently playing book from context
  return books[0] || null;
}

// Mock TTS function
export async function callTTS(text: string, voiceId: string): Promise<string> {
  // Simulate API call delay
  await new Promise(resolve => setTimeout(resolve, 1000));
  
  // Return a mock audio URL
  return `/api/tts?text=${encodeURIComponent(text)}&voice=${voiceId}`;
} 