import type { Book } from "@/types/book"

// Mock data for books
const books: Book[] = [
  // Existing books
  {
    id: "pride-and-prejudice",
    title: "Pride and Prejudice",
    author: "Jane Austen",
    description:
      "Pride and Prejudice follows the turbulent relationship between Elizabeth Bennet, the daughter of a country gentleman, and Fitzwilliam Darcy, a rich aristocratic landowner. They must overcome the titular sins of pride and prejudice in order to fall in love and marry.",
    coverUrl: "/pride-and-prejudice-cover.png",
    genres: ["Classics", "Romance", "Fiction"],
    duration: "11h",
    pages: 432,
    chapters: [
      { id: "ch-1", title: "Chapter 1", duration: "15m", audioUrl: "/audio/pride-and-prejudice/ch-1.mp3" },
      { id: "ch-2", title: "Chapter 2", duration: "18m", audioUrl: "/audio/pride-and-prejudice/ch-2.mp3" },
      { id: "ch-3", title: "Chapter 3", duration: "20m", audioUrl: "/audio/pride-and-prejudice/ch-3.mp3" },
      { id: "ch-4", title: "Chapter 4", duration: "17m", audioUrl: "/audio/pride-and-prejudice/ch-4.mp3" },
      { id: "ch-5", title: "Chapter 5", duration: "16m", audioUrl: "/audio/pride-and-prejudice/ch-5.mp3" },
      // More chapters would be added here
    ],
  },
  {
    id: "the-great-gatsby",
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    description:
      "Set in the Jazz Age on Long Island, the novel depicts narrator Nick Carraway's interactions with mysterious millionaire Jay Gatsby and Gatsby's obsession to reunite with his former lover, Daisy Buchanan. A tale of wealth, love, and the American Dream.",
    coverUrl: "/great-gatsby-cover.png",
    genres: ["Classics", "Fiction", "Literary"],
    duration: "5h",
    pages: 180,
    chapters: [
      { id: "ch-1", title: "Chapter 1", duration: "25m", audioUrl: "/audio/great-gatsby/ch-1.mp3" },
      { id: "ch-2", title: "Chapter 2", duration: "22m", audioUrl: "/audio/great-gatsby/ch-2.mp3" },
      { id: "ch-3", title: "Chapter 3", duration: "28m", audioUrl: "/audio/great-gatsby/ch-3.mp3" },
      { id: "ch-4", title: "Chapter 4", duration: "24m", audioUrl: "/audio/great-gatsby/ch-4.mp3" },
      { id: "ch-5", title: "Chapter 5", duration: "26m", audioUrl: "/audio/great-gatsby/ch-5.mp3" },
      // More chapters would be added here
    ],
  },
  {
    id: "mrs-dalloway",
    title: "Mrs Dalloway",
    author: "Virginia Woolf",
    description:
      "The novel details a day in the life of Clarissa Dalloway, a fictional high-society woman in post-First World War England. It addresses the nature of time in personal experience through multiple interwoven stories, particularly that of Clarissa and Septimus Warren Smith.",
    coverUrl: "/mrs-dalloway-cover.png",
    genres: ["Classics", "Literary", "Modernist"],
    duration: "6h",
    pages: 216,
    chapters: [
      { id: "ch-1", title: "Morning", duration: "1h 10m", audioUrl: "/audio/mrs-dalloway/ch-1.mp3" },
      { id: "ch-2", title: "Afternoon", duration: "1h 25m", audioUrl: "/audio/mrs-dalloway/ch-2.mp3" },
      { id: "ch-3", title: "Evening", duration: "1h 15m", audioUrl: "/audio/mrs-dalloway/ch-3.mp3" },
      { id: "ch-4", title: "Night", duration: "1h 20m", audioUrl: "/audio/mrs-dalloway/ch-4.mp3" },
      { id: "ch-5", title: "Epilogue", duration: "50m", audioUrl: "/audio/mrs-dalloway/ch-5.mp3" },
    ],
  },
  {
    id: "the-sun-also-rises",
    title: "The Sun Also Rises",
    author: "Ernest Hemingway",
    description:
      "The novel follows a group of American and British expatriates who travel from Paris to the Festival of San Fermín in Pamplona to watch the running of the bulls and the bullfights. An early modernist novel, it received mixed reviews upon publication but is now recognized as Hemingway's greatest work.",
    coverUrl: "/sun-also-rises-cover.png",
    genres: ["Classics", "Fiction", "Modernist"],
    duration: "7h",
    pages: 256,
    chapters: [
      { id: "ch-1", title: "Book 1, Chapter 1", duration: "30m", audioUrl: "/audio/sun-also-rises/ch-1.mp3" },
      { id: "ch-2", title: "Book 1, Chapter 2", duration: "35m", audioUrl: "/audio/sun-also-rises/ch-2.mp3" },
      { id: "ch-3", title: "Book 1, Chapter 3", duration: "32m", audioUrl: "/audio/sun-also-rises/ch-3.mp3" },
      { id: "ch-4", title: "Book 2, Chapter 1", duration: "34m", audioUrl: "/audio/sun-also-rises/ch-4.mp3" },
      { id: "ch-5", title: "Book 2, Chapter 2", duration: "31m", audioUrl: "/audio/sun-also-rises/ch-5.mp3" },
      // More chapters would be added here
    ],
  },
  {
    id: "winnie-the-pooh",
    title: "Winnie-the-Pooh",
    author: "A. A. Milne",
    description:
      "The adventures of Christopher Robin and his friends, in which Pooh Bear uses a balloon to get honey, Piglet meets a Heffalump, Eeyore loses a tail, and more. These tales of adventure in the Hundred Acre Wood have delighted generations of children.",
    coverUrl: "/winnie-the-pooh-cover.png",
    genres: ["Children", "Classics", "Fantasy"],
    duration: "2h 30m",
    pages: 176,
    chapters: [
      { id: "ch-1", title: "In Which We Are Introduced", duration: "15m", audioUrl: "/audio/winnie-the-pooh/ch-1.mp3" },
      { id: "ch-2", title: "In Which Pooh Goes Visiting", duration: "18m", audioUrl: "/audio/winnie-the-pooh/ch-2.mp3" },
      { id: "ch-3", title: "In Which Pooh and Piglet Go Hunting", duration: "17m", audioUrl: "/audio/winnie-the-pooh/ch-3.mp3" },
      { id: "ch-4", title: "In Which Eeyore Loses a Tail", duration: "16m", audioUrl: "/audio/winnie-the-pooh/ch-4.mp3" },
      { id: "ch-5", title: "In Which Piglet Meets a Heffalump", duration: "19m", audioUrl: "/audio/winnie-the-pooh/ch-5.mp3" },
      // More chapters would be added here
    ],
  },
  {
    id: "sherlock-holmes",
    title: "Sherlock Holmes Short Stories",
    author: "Arthur Conan Doyle",
    description:
      "A collection of twelve short stories featuring the famous detective Sherlock Holmes and his friend Dr. Watson. These stories showcase Holmes's brilliant deductive reasoning as he solves seemingly impossible mysteries.",
    coverUrl: "/sherlock-holmes-cover.png",
    genres: ["Classics", "Mystery", "Detective"],
    duration: "10h",
    pages: 320,
    chapters: [
      { id: "ch-1", title: "A Scandal in Bohemia", duration: "45m", audioUrl: "/audio/sherlock-holmes/ch-1.mp3" },
      { id: "ch-2", title: "The Red-Headed League", duration: "42m", audioUrl: "/audio/sherlock-holmes/ch-2.mp3" },
      { id: "ch-3", title: "A Case of Identity", duration: "38m", audioUrl: "/audio/sherlock-holmes/ch-3.mp3" },
      { id: "ch-4", title: "The Boscombe Valley Mystery", duration: "47m", audioUrl: "/audio/sherlock-holmes/ch-4.mp3" },
      { id: "ch-5", title: "The Five Orange Pips", duration: "40m", audioUrl: "/audio/sherlock-holmes/ch-5.mp3" },
      // More chapters would be added here
    ],
  },
  {
    id: "frankenstein",
    title: "Frankenstein",
    author: "Mary Shelley",
    description:
      "The story of Victor Frankenstein, a young scientist who creates a sapient creature in an unorthodox scientific experiment. Shelley's novel raises profound questions about the nature of humanity and the responsibilities of creators toward their creations.",
    coverUrl: "/frankenstein-cover.png",
    genres: ["Classics", "Horror", "Gothic", "Science Fiction"],
    duration: "8h",
    pages: 280,
    chapters: [
      { id: "ch-1", title: "Letter 1", duration: "15m", audioUrl: "/audio/frankenstein/ch-1.mp3" },
      { id: "ch-2", title: "Letter 2", duration: "12m", audioUrl: "/audio/frankenstein/ch-2.mp3" },
      { id: "ch-3", title: "Letter 3", duration: "10m", audioUrl: "/audio/frankenstein/ch-3.mp3" },
      { id: "ch-4", title: "Letter 4", duration: "25m", audioUrl: "/audio/frankenstein/ch-4.mp3" },
      { id: "ch-5", title: "Chapter 1", duration: "20m", audioUrl: "/audio/frankenstein/ch-5.mp3" },
      // More chapters would be added here
    ],
  },
  {
    id: "dracula",
    title: "Dracula",
    author: "Bram Stoker",
    description:
      "The novel tells the story of Dracula's attempt to move from Transylvania to England so that he may find new blood and spread the undead curse, and of the battle between Dracula and a small group of people led by Professor Abraham Van Helsing.",
    coverUrl: "/dracula-cover.png",
    genres: ["Classics", "Horror", "Gothic"],
    duration: "15h",
    pages: 418,
    chapters: [
      { id: "ch-1", title: "Jonathan Harker's Journal", duration: "1h 10m", audioUrl: "/audio/dracula/ch-1.mp3" },
      { id: "ch-2", title: "Letter From Miss Mina Murray", duration: "55m", audioUrl: "/audio/dracula/ch-2.mp3" },
      { id: "ch-3", title: "Lucy Westenra's Diary", duration: "1h 5m", audioUrl: "/audio/dracula/ch-3.mp3" },
      { id: "ch-4", title: "Dr. Seward's Diary", duration: "1h 15m", audioUrl: "/audio/dracula/ch-4.mp3" },
      { id: "ch-5", title: "Letters", duration: "50m", audioUrl: "/audio/dracula/ch-5.mp3" },
      // More chapters would be added here
    ],
  },
  {
    id: "frederick-douglass",
    title: "Narrative of the Life of Frederick Douglass",
    author: "Frederick Douglass",
    description:
      "Narrative of the Life of Frederick Douglass is an 1845 memoir and treatise on abolition written by famous orator and former slave Frederick Douglass during his time in Lynn, Massachusetts.",
    coverUrl: "/frederick-douglass-memoir-cover.png",
    genres: ["Classics", "Biography", "History"],
    duration: "4h",
    pages: 158,
    chapters: [
      { id: "ch-1", title: "Chapter 1", duration: "22m", audioUrl: "/audio/frederick-douglass/ch-1.mp3" },
      { id: "ch-2", title: "Chapter 2", duration: "19m", audioUrl: "/audio/frederick-douglass/ch-2.mp3" },
      { id: "ch-3", title: "Chapter 3", duration: "21m", audioUrl: "/audio/frederick-douglass/ch-3.mp3" },
      { id: "ch-4", title: "Chapter 4", duration: "20m", audioUrl: "/audio/frederick-douglass/ch-4.mp3" },
      { id: "ch-5", title: "Chapter 5", duration: "18m", audioUrl: "/audio/frederick-douglass/ch-5.mp3" },
      // More chapters would be added here
    ],
  },
  {
    id: "the-secret-garden",
    title: "The Secret Garden",
    author: "Frances Hodgson Burnett",
    description:
      "The story of Mary Lennox, a sickly and unloved 10-year-old girl who is born in India to wealthy British parents. She is sent to England to live with her uncle after her parents die from cholera. There, she discovers a walled garden which has been kept secret for years.",
    coverUrl: "/secret-garden-cover.png",
    genres: ["Classics", "Children", "Fiction"],
    duration: "8h",
    pages: 288,
    chapters: [
      { id: "ch-1", title: "There Is No One Left", duration: "25m", audioUrl: "/audio/secret-garden/ch-1.mp3" },
      { id: "ch-2", title: "Mistress Mary Quite Contrary", duration: "22m", audioUrl: "/audio/secret-garden/ch-2.mp3" },
      { id: "ch-3", title: "Across the Moor", duration: "24m", audioUrl: "/audio/secret-garden/ch-3.mp3" },
      { id: "ch-4", title: "Martha", duration: "26m", audioUrl: "/audio/secret-garden/ch-4.mp3" },
      { id: "ch-5", title: "The Cry in the Corridor", duration: "23m", audioUrl: "/audio/secret-garden/ch-5.mp3" },
      // More chapters would be added here
    ],
  },
  {
    id: "call-of-cthulhu",
    title: "The Call of Cthulhu",
    author: "H. P. Lovecraft",
    description:
      "The story is presented as a manuscript found among the papers of the late Francis Wayland Thurston, recounting his discovery of notes left by his grand-uncle, a professor at Brown University. The notes reveal the existence of a cult dedicated to the worship of the ancient, cosmic entity Cthulhu.",
    coverUrl: "/call-of-cthulhu-cover.png",
    genres: ["Horror", "Cosmic Horror", "Short Story"],
    duration: "2h",
    pages: 64,
    chapters: [
      { id: "ch-1", title: "The Horror in Clay", duration: "30m", audioUrl: "/audio/call-of-cthulhu/ch-1.mp3" },
      { id: "ch-2", title: "The Tale of Inspector Legrasse", duration: "45m", audioUrl: "/audio/call-of-cthulhu/ch-2.mp3" },
      { id: "ch-3", title: "The Madness from the Sea", duration: "45m", audioUrl: "/audio/call-of-cthulhu/ch-3.mp3" },
    ],
  },
  {
    id: "the-prophet",
    title: "The Prophet",
    author: "Kahlil Gibran",
    description:
      "The book is a collection of 26 poetic essays covering all aspects of human life, including love, marriage, children, giving, eating and drinking, work, joy and sorrow, housing, clothes, buying and selling, crime and punishment, laws, freedom, reason and passion, pain, self-knowledge, teaching, friendship, talking, time, good and evil, prayer, pleasure, beauty, religion, and death.",
    coverUrl: "/the-prophet-cover.png",
    genres: ["Poetry", "Philosophy", "Spirituality"],
    duration: "2h",
    pages: 96,
    chapters: [
      { id: "ch-1", title: "The Coming of the Ship", duration: "5m", audioUrl: "/audio/the-prophet/ch-1.mp3" },
      { id: "ch-2", title: "On Love", duration: "7m", audioUrl: "/audio/the-prophet/ch-2.mp3" },
      { id: "ch-3", title: "On Marriage", duration: "6m", audioUrl: "/audio/the-prophet/ch-3.mp3" },
      { id: "ch-4", title: "On Children", duration: "5m", audioUrl: "/audio/the-prophet/ch-4.mp3" },
      { id: "ch-5", title: "On Giving", duration: "6m", audioUrl: "/audio/the-prophet/ch-5.mp3" },
      // More chapters would be added here
    ],
  },
  {
    id: "peter-pan",
    title: "Peter Pan",
    author: "J. M. Barrie",
    description:
      "The magical story of Peter Pan, the boy who never grew up. Peter teaches Wendy, John, and Michael Darling to fly and takes them to the island of Neverland, where they have adventures with mermaids, Indians, and pirates, especially the villainous Captain Hook.",
    coverUrl: "/peter-pan-cover.png",
    genres: ["Children", "Fantasy", "Adventure"],
    duration: "5h",
    pages: 208,
    chapters: [
      { id: "ch-1", title: "Peter Breaks Through", duration: "20m", audioUrl: "/audio/peter-pan/ch-1.mp3" },
      { id: "ch-2", title: "The Shadow", duration: "18m", audioUrl: "/audio/peter-pan/ch-2.mp3" },
      { id: "ch-3", title: "Come Away, Come Away!", duration: "22m", audioUrl: "/audio/peter-pan/ch-3.mp3" },
      { id: "ch-4", title: "The Flight", duration: "19m", audioUrl: "/audio/peter-pan/ch-4.mp3" },
      { id: "ch-5", title: "The Island Come True", duration: "21m", audioUrl: "/audio/peter-pan/ch-5.mp3" },
      // More chapters would be added here
    ],
  },
  {
    id: "room-with-a-view",
    title: "A Room With a View",
    author: "E. M. Forster",
    description:
      "The story of a young English woman, Lucy Honeychurch, whose trip to Italy with her cousin Charlotte Bartlett leads to an internal struggle between the demands of social convention and the stirrings of her passionate, independent nature, especially after meeting the unconventional George Emerson.",
    coverUrl: "/room-with-a-view-cover.png",
    genres: ["Classics", "Romance", "Fiction"],
    duration: "6h",
    pages: 240,
    chapters: [
      { id: "ch-1", title: "The Bertolini", duration: "25m", audioUrl: "/audio/room-with-a-view/ch-1.mp3" },
      { id: "ch-2", title: "In Santa Croce with No Baedeker", duration: "28m", audioUrl: "/audio/room-with-a-view/ch-2.mp3" },
      { id: "ch-3", title: "Music, Violets, and the Letter S", duration: "26m", audioUrl: "/audio/room-with-a-view/ch-3.mp3" },
      { id: "ch-4", title: "Fourth Chapter", duration: "24m", audioUrl: "/audio/room-with-a-view/ch-4.mp3" },
      { id: "ch-5", title: "Possibilities of a Pleasant Outing", duration: "27m", audioUrl: "/audio/room-with-a-view/ch-5.mp3" },
      // More chapters would be added here
    ],
  },
  {
    id: "art-of-war",
    title: "The Art of War",
    author: "Sun Tzu",
    description:
      "An ancient Chinese military treatise dating from the Late Spring and Autumn Period. The work, which is attributed to the ancient Chinese military strategist Sun Tzu, is composed of 13 chapters. Each one is devoted to an aspect of warfare and how it applies to military strategy and tactics.",
    coverUrl: "/art-of-war-cover.png",
    genres: ["Classics", "Philosophy", "Military"],
    duration: "1h 30m",
    pages: 112,
    chapters: [
      { id: "ch-1", title: "Laying Plans", duration: "7m", audioUrl: "/audio/art-of-war/ch-1.mp3" },
      { id: "ch-2", title: "Waging War", duration: "6m", audioUrl: "/audio/art-of-war/ch-2.mp3" },
      { id: "ch-3", title: "Attack by Stratagem", duration: "8m", audioUrl: "/audio/art-of-war/ch-3.mp3" },
      { id: "ch-4", title: "Tactical Dispositions", duration: "7m", audioUrl: "/audio/art-of-war/ch-4.mp3" },
      { id: "ch-5", title: "Energy", duration: "7m", audioUrl: "/audio/art-of-war/ch-5.mp3" },
      // More chapters would be added here
    ],
  },
  {
    id: "moby-dick",
    title: "Moby Dick",
    author: "Herman Melville",
    description: "The story of Captain Ahab's obsessive quest to hunt down the white whale that took his leg. A masterpiece of American literature that explores themes of revenge, obsession, and man's relationship with nature.",
    coverUrl: "/generated-covers/moby-dick.png",
    genres: ["Classics", "Adventure", "Literary"],
    duration: "24h",
    pages: 635,
    chapters: [
      { id: "ch-1", title: "Loomings", duration: "45m", audioUrl: "/audio/moby-dick/ch-1.mp3" },
      { id: "ch-2", title: "The Carpet-Bag", duration: "40m", audioUrl: "/audio/moby-dick/ch-2.mp3" },
      { id: "ch-3", title: "The Spouter-Inn", duration: "42m", audioUrl: "/audio/moby-dick/ch-3.mp3" },
      { id: "ch-4", title: "The Counterpane", duration: "38m", audioUrl: "/audio/moby-dick/ch-4.mp3" },
      { id: "ch-5", title: "Breakfast", duration: "35m", audioUrl: "/audio/moby-dick/ch-5.mp3" },
    ],
  },
  {
    id: "adventures-of-huckleberry-finn",
    title: "Adventures of Huckleberry Finn",
    author: "Mark Twain",
    description:
      "Commonly named among the Great American Novels, the work is among the first in major American literature to be written throughout in vernacular English, characterized by local color regionalism. It is told in the first person by Huckleberry 'Huck' Finn, the narrator of two other Twain novels and a friend of Tom Sawyer.",
    coverUrl: "/huckleberry-finn-cover.png",
    genres: ["Classics", "Adventure", "Satire"],
    duration: "11h 15m",
    pages: 366,
    chapters: [
      { id: "ch-1", title: "Chapter 1", duration: "18m", audioUrl: "/audio/huckleberry-finn/ch-1.mp3" },
      { id: "ch-2", title: "Chapter 2", duration: "22m", audioUrl: "/audio/huckleberry-finn/ch-2.mp3" },
      { id: "ch-3", title: "Chapter 3", duration: "19m", audioUrl: "/audio/huckleberry-finn/ch-3.mp3" },
      { id: "ch-4", title: "Chapter 4", duration: "21m", audioUrl: "/audio/huckleberry-finn/ch-4.mp3" },
      { id: "ch-5", title: "Chapter 5", duration: "17m", audioUrl: "/audio/huckleberry-finn/ch-5.mp3" },
      // More chapters would be added here
    ],
  },
  {
    id: "picture-of-dorian-gray",
    title: "The Picture of Dorian Gray",
    author: "Oscar Wilde",
    description:
      "The novel tells of a young man named Dorian Gray, the subject of a painting by artist Basil Hallward. Basil is impressed by Dorian's beauty and becomes infatuated with him, believing his beauty is responsible for a new mode in his art. Dorian meets Lord Henry Wotton, a friend of Basil's, and becomes enthralled by Lord Henry's world view.",
    coverUrl: "/dorian-gray-cover.png",
    genres: ["Classics", "Gothic", "Horror", "Philosophical"],
    duration: "8h 45m",
    pages: 254,
    chapters: [
      { id: "ch-1", title: "Chapter 1", duration: "35m", audioUrl: "/audio/dorian-gray/ch-1.mp3" },
      { id: "ch-2", title: "Chapter 2", duration: "32m", audioUrl: "/audio/dorian-gray/ch-2.mp3" },
      { id: "ch-3", title: "Chapter 3", duration: "28m", audioUrl: "/audio/dorian-gray/ch-3.mp3" },
      { id: "ch-4", title: "Chapter 4", duration: "30m", audioUrl: "/audio/dorian-gray/ch-4.mp3" },
      { id: "ch-5", title: "Chapter 5", duration: "33m", audioUrl: "/audio/dorian-gray/ch-5.mp3" },
      // More chapters would be added here
    ],
  },
  {
    id: "little-women",
    title: "Little Women",
    author: "Louisa May Alcott",
    description:
      "The novel follows the lives of the four March sisters—Meg, Jo, Beth, and Amy—and details their passage from childhood to womanhood. It is loosely based on the lives of the author and her three sisters. Scholars classify it as an autobiographical or semi-autobiographical novel.",
    coverUrl: "/little-women-cover.png",
    genres: ["Classics", "Fiction", "Coming of Age"],
    duration: "17h 30m",
    pages: 449,
    chapters: [
      { id: "ch-1", title: "Playing Pilgrims", duration: "28m", audioUrl: "/audio/little-women/ch-1.mp3" },
      { id: "ch-2", title: "A Merry Christmas", duration: "32m", audioUrl: "/audio/little-women/ch-2.mp3" },
      { id: "ch-3", title: "The Laurence Boy", duration: "30m", audioUrl: "/audio/little-women/ch-3.mp3" },
      { id: "ch-4", title: "Burdens", duration: "25m", audioUrl: "/audio/little-women/ch-4.mp3" },
      { id: "ch-5", title: "Being Neighborly", duration: "29m", audioUrl: "/audio/little-women/ch-5.mp3" },
      // More chapters would be added here
    ],
  },
  {
    id: "scarlet-letter",
    title: "The Scarlet Letter",
    author: "Nathaniel Hawthorne",
    description:
      "Set in Puritan Massachusetts Bay Colony during the years 1642 to 1649, the novel tells the story of Hester Prynne, who conceives a daughter through an affair and then struggles to create a new life of repentance and dignity. Throughout the book, Hawthorne explores themes of legalism, sin, and guilt.",
    coverUrl: "/scarlet-letter-cover.png",
    genres: ["Classics", "Historical Fiction", "Romance"],
    duration: "7h 45m",
    pages: 238,
    chapters: [
      { id: "ch-1", title: "The Prison Door", duration: "10m", audioUrl: "/audio/scarlet-letter/ch-1.mp3" },
      { id: "ch-2", title: "The Market Place", duration: "25m", audioUrl: "/audio/scarlet-letter/ch-2.mp3" },
      { id: "ch-3", title: "The Recognition", duration: "22m", audioUrl: "/audio/scarlet-letter/ch-3.mp3" },
      { id: "ch-4", title: "The Interview", duration: "20m", audioUrl: "/audio/scarlet-letter/ch-4.mp3" },
      { id: "ch-5", title: "Hester at Her Needle", duration: "24m", audioUrl: "/audio/scarlet-letter/ch-5.mp3" },
      // More chapters would be added here
    ],
  },
  {
    id: "odyssey",
    title: "The Odyssey",
    author: "Homer",
    description: "The epic tale of Odysseus's ten-year journey home after the Trojan War. Facing mythical creatures, vengeful gods, and treacherous seas, Odysseus must use his wit and courage to return to his kingdom of Ithaca.",
    coverUrl: "/odyssey-cover.png",
    genres: ["Classics", "Epic Poetry", "Greek Literature", "Adventure"],
    duration: "14h 30m",
    pages: 541,
    chapters: [
      { id: "ch-1", title: "Book I: Athena Inspires the Prince", duration: "40m", audioUrl: "/audio/odyssey/ch-1.mp3" },
      { id: "ch-2", title: "Book II: Telemachus Sets Sail", duration: "38m", audioUrl: "/audio/odyssey/ch-2.mp3" },
      { id: "ch-3", title: "Book III: King Nestor Remembers", duration: "42m", audioUrl: "/audio/odyssey/ch-3.mp3" },
      { id: "ch-4", title: "Book IV: The King and Queen of Sparta", duration: "45m", audioUrl: "/audio/odyssey/ch-4.mp3" },
      { id: "ch-5", title: "Book V: Odysseus—Nymph and Shipwreck", duration: "39m", audioUrl: "/audio/odyssey/ch-5.mp3" },
    ],
  },
  {
    id: "count-of-monte-cristo",
    title: "The Count of Monte Cristo",
    author: "Alexandre Dumas",
    description:
      "The story takes place in France, Italy, and islands in the Mediterranean during the historical events of 1815–1839: the era of the Bourbon Restoration through the reign of Louis-Philippe of France. It begins on the day that Napoleon left his first island of exile, Elba, beginning the Hundred Days period when Napoleon returned to power.",
    coverUrl: "/monte-cristo-cover.png",
    genres: ["Classics", "Adventure", "Historical Fiction"],
    duration: "52h 30m",
    pages: 1276,
    chapters: [
      { id: "ch-1", title: "Marseilles—The Arrival", duration: "35m", audioUrl: "/audio/monte-cristo/ch-1.mp3" },
      { id: "ch-2", title: "Father and Son", duration: "32m", audioUrl: "/audio/monte-cristo/ch-2.mp3" },
      { id: "ch-3", title: "The Catalans", duration: "30m", audioUrl: "/audio/monte-cristo/ch-3.mp3" },
      { id: "ch-4", title: "Conspiracy", duration: "28m", audioUrl: "/audio/monte-cristo/ch-4.mp3" },
      { id: "ch-5", title: "The Marriage Feast", duration: "33m", audioUrl: "/audio/monte-cristo/ch-5.mp3" },
      // More chapters would be added here
    ],
  },
  {
    id: "war-and-peace",
    title: "War and Peace",
    author: "Leo Tolstoy",
    description:
      "Epic in scale, War and Peace delineates in graphic detail events leading up to Napoleon's invasion of Russia, and the impact of the Napoleonic era on Tsarist society, as seen through the eyes of five Russian aristocratic families.",
    coverUrl: "/war-and-peace-cover.png",
    genres: ["Classics", "Historical Fiction", "Literary"],
    duration: "60h 45m",
    pages: 1225,
    chapters: [
      { id: "ch-1", title: "Book One: 1805, Chapter 1", duration: "18m", audioUrl: "/audio/war-and-peace/ch-1.mp3" },
      { id: "ch-2", title: "Book One: 1805, Chapter 2", duration: "22m", audioUrl: "/audio/war-and-peace/ch-2.mp3" },
      { id: "ch-3", title: "Book One: 1805, Chapter 3", duration: "20m", audioUrl: "/audio/war-and-peace/ch-3.mp3" },
      { id: "ch-4", title: "Book One: 1805, Chapter 4", duration: "19m", audioUrl: "/audio/war-and-peace/ch-4.mp3" },
      { id: "ch-5", title: "Book One: 1805, Chapter 5", duration: "21m", audioUrl: "/audio/war-and-peace/ch-5.mp3" },
      // More chapters would be added here
    ],
  },
  {
    id: "jungle-book",
    title: "The Jungle Book",
    author: "Rudyard Kipling",
    description:
      "The Jungle Book is a collection of stories by the English author Rudyard Kipling. Most of the characters are animals such as Shere Khan the tiger and Baloo the bear, though a principal character is the boy or 'man-cub' Mowgli, who is raised in the jungle by wolves.",
    coverUrl: "/jungle-book-cover.png",
    genres: ["Classics", "Children", "Adventure"],
    duration: "5h 15m",
    pages: 277,
    chapters: [
      { id: "ch-1", title: "Mowgli's Brothers", duration: "45m", audioUrl: "/audio/jungle-book/ch-1.mp3" },
      { id: "ch-2", title: "Hunting-Song of the Seeonee Pack", duration: "5m", audioUrl: "/audio/jungle-book/ch-2.mp3" },
      { id: "ch-3", title: "Kaa's Hunting", duration: "50m", audioUrl: "/audio/jungle-book/ch-3.mp3" },
      { id: "ch-4", title: "Road-Song of the Bandar-Log", duration: "5m", audioUrl: "/audio/jungle-book/ch-4.mp3" },
      { id: "ch-5", title: "Tiger! Tiger!", duration: "40m", audioUrl: "/audio/jungle-book/ch-5.mp3" },
      // More chapters would be added here
    ],
  },
  {
    id: "time-machine",
    title: "The Time Machine",
    author: "H.G. Wells",
    description: "A Victorian scientist travels far into the future and encounters strange civilizations.",
    coverUrl: "/time-machine-cover.png",
    genres: ["Classics", "Science Fiction", "Adventure"],
    duration: "5h",
    pages: 232,
    chapters: [
      { id: "ch-1", title: "Introduction", duration: "15m", audioUrl: "/audio/time-machine/ch-1.mp3" },
      { id: "ch-2", title: "The Machine", duration: "20m", audioUrl: "/audio/time-machine/ch-2.mp3" },
      { id: "ch-3", title: "The Time Traveller Returns", duration: "25m", audioUrl: "/audio/time-machine/ch-3.mp3" },
      { id: "ch-4", title: "The Future", duration: "30m", audioUrl: "/audio/time-machine/ch-4.mp3" },
      { id: "ch-5", title: "The Morlocks", duration: "35m", audioUrl: "/audio/time-machine/ch-5.mp3" },
      // More chapters would be added here
    ],
  },
  {
    id: "importance-of-being-earnest",
    title: "The Importance of Being Earnest",
    author: "Oscar Wilde",
    description:
      "The Importance of Being Earnest, A Trivial Comedy for Serious People is a play by Oscar Wilde. First performed on 14 February 1895 at the St James's Theatre in London, it is a farcical comedy in which the protagonists maintain fictitious personae to escape burdensome social obligations.",
    coverUrl: "/earnest-cover.png",
    genres: ["Classics", "Comedy", "Play"],
    duration: "2h 15m",
    pages: 76,
    chapters: [
      { id: "ch-1", title: "Act 1", duration: "45m", audioUrl: "/audio/importance-of-being-earnest/ch-1.mp3" },
      { id: "ch-2", title: "Act 2", duration: "40m", audioUrl: "/audio/importance-of-being-earnest/ch-2.mp3" },
      { id: "ch-3", title: "Act 3", duration: "50m", audioUrl: "/audio/importance-of-being-earnest/ch-3.mp3" },
    ],
  },
  {
    id: "wuthering-heights",
    title: "Wuthering Heights",
    author: "Emily Brontë",
    description:
      "Wuthering Heights is Emily Brontë's only novel. It was first published in 1847 under the pseudonym Ellis Bell, and a posthumous second edition was edited by her sister Charlotte. The name of the novel comes from the Yorkshire manor on the moors on which the story centers.",
    coverUrl: "/wuthering-heights-cover.png",
    genres: ["Classics", "Gothic", "Romance"],
    duration: "13h 45m",
    pages: 532,
    chapters: [
      { id: "ch-1", title: "Chapter 1", duration: "28m", audioUrl: "/audio/wuthering-heights/ch-1.mp3" },
      { id: "ch-2", title: "Chapter 2", duration: "25m", audioUrl: "/audio/wuthering-heights/ch-2.mp3" },
      { id: "ch-3", title: "Chapter 3", duration: "30m", audioUrl: "/audio/wuthering-heights/ch-3.mp3" },
      { id: "ch-4", title: "Chapter 4", duration: "32m", audioUrl: "/audio/wuthering-heights/ch-4.mp3" },
      { id: "ch-5", title: "Chapter 5", duration: "27m", audioUrl: "/audio/wuthering-heights/ch-5.mp3" },
      // More chapters would be added here
    ],
  },
  {
    id: "jane-eyre",
    title: "Jane Eyre",
    author: "Charlotte Brontë",
    description:
      "Jane Eyre follows the experiences of its eponymous heroine, including her growth to adulthood and her love for Mr. Rochester, the brooding master of Thornfield Hall. The novel revolutionized prose fiction by being the first to focus on its protagonist's moral and spiritual development through an intimate first-person narrative.",
    coverUrl: "/jane-eyre-cover.png",
    genres: ["Classics", "Gothic", "Romance"],
    duration: "18h 30m",
    pages: 532,
    chapters: [
      { id: "ch-1", title: "Chapter 1", duration: "22m", audioUrl: "/audio/jane-eyre/ch-1.mp3" },
      { id: "ch-2", title: "Chapter 2", duration: "25m", audioUrl: "/audio/jane-eyre/ch-2.mp3" },
      { id: "ch-3", title: "Chapter 3", duration: "20m", audioUrl: "/audio/jane-eyre/ch-3.mp3" },
      { id: "ch-4", title: "Chapter 4", duration: "24m", audioUrl: "/audio/jane-eyre/ch-4.mp3" },
      { id: "ch-5", title: "Chapter 5", duration: "23m", audioUrl: "/audio/jane-eyre/ch-5.mp3" },
      // More chapters would be added here
    ],
  },
  {
    id: "republic",
    title: "The Republic",
    author: "Plato",
    description:
      "The Republic is a Socratic dialogue, authored by Plato around 375 BCE, concerning justice, the order and character of the just city-state, and the just man. It is Plato's best-known work, and has proven to be one of the world's most influential works of philosophy and political theory.",
    coverUrl: "/republic-cover.png",
    genres: ["Classics", "Philosophy", "Political"],
    duration: "12h 15m",
    pages: 416,
    chapters: [
      { id: "ch-1", title: "Book I", duration: "1h 5m", audioUrl: "/audio/republic/ch-1.mp3" },
      { id: "ch-2", title: "Book II", duration: "1h 10m", audioUrl: "/audio/republic/ch-2.mp3" },
      { id: "ch-3", title: "Book III", duration: "1h 15m", audioUrl: "/audio/republic/ch-3.mp3" },
      { id: "ch-4", title: "Book IV", duration: "1h 5m", audioUrl: "/audio/republic/ch-4.mp3" },
      { id: "ch-5", title: "Book V", duration: "1h 20m", audioUrl: "/audio/republic/ch-5.mp3" },
      // More chapters would be added here
    ],
  },
  {
    id: "iliad",
    title: "The Iliad",
    author: "Homer",
    description: "An epic poem set during the Trojan War, focusing on the quarrel between King Agamemnon and the warrior Achilles. The poem explores themes of glory, honor, and the human cost of war.",
    coverUrl: "/iliad-cover.png",
    genres: ["Classics", "Epic Poetry", "Greek Literature"],
    duration: "16h 45m",
    pages: 683,
    chapters: [
      { id: "ch-1", title: "Book I: The Rage of Achilles", duration: "45m", audioUrl: "/audio/iliad/ch-1.mp3" },
      { id: "ch-2", title: "Book II: The Great Gathering of Armies", duration: "42m", audioUrl: "/audio/iliad/ch-2.mp3" },
      { id: "ch-3", title: "Book III: Helen Reviews the Champions", duration: "38m", audioUrl: "/audio/iliad/ch-3.mp3" },
      { id: "ch-4", title: "Book IV: The Truce Erupts in War", duration: "40m", audioUrl: "/audio/iliad/ch-4.mp3" },
      { id: "ch-5", title: "Book V: Diomedes Fights the Gods", duration: "44m", audioUrl: "/audio/iliad/ch-5.mp3" },
    ],
  },
  {
    id: "don-quixote",
    title: "Don Quixote",
    author: "Miguel de Cervantes",
    description:
      "The plot revolves around the adventures of a noble from La Mancha named Alonso Quixano, who reads so many chivalric romances that he loses his mind and decides to become a knight-errant to revive chivalry and serve his nation, under the name Don Quixote de la Mancha.",
    coverUrl: "/don-quixote-cover.png",
    genres: ["Classics", "Satire", "Adventure"],
    duration: "36h 45m",
    pages: 863,
    chapters: [
      { id: "ch-1", title: "Part 1, Chapter 1", duration: "25m", audioUrl: "/audio/don-quixote/ch-1.mp3" },
      { id: "ch-2", title: "Part 1, Chapter 2", duration: "28m", audioUrl: "/audio/don-quixote/ch-2.mp3" },
      { id: "ch-3", title: "Part 1, Chapter 3", duration: "22m", audioUrl: "/audio/don-quixote/ch-3.mp3" },
      { id: "ch-4", title: "Part 1, Chapter 4", duration: "24m", audioUrl: "/audio/don-quixote/ch-4.mp3" },
      { id: "ch-5", title: "Part 1, Chapter 5", duration: "26m", audioUrl: "/audio/don-quixote/ch-5.mp3" },
      // More chapters would be added here
    ],
  },
  {
    id: "divine-comedy",
    title: "The Divine Comedy",
    author: "Dante Alighieri",
    description:
      "The Divine Comedy is an Italian narrative poem by Dante Alighieri, which is widely considered the pre-eminent work in Italian literature and one of the greatest works of world literature. The poem's imaginative vision of the afterlife is representative of the medieval world-view as it had developed in the Western Church.",
    coverUrl: "/divine-comedy-cover.png",
    genres: ["Classics", "Epic Poetry", "Religious"],
    duration: "12h 30m",
    pages: 432,
    chapters: [
      { id: "ch-1", title: "Inferno, Canto I", duration: "15m", audioUrl: "/audio/divine-comedy/ch-1.mp3" },
      { id: "ch-2", title: "Inferno, Canto II", duration: "18m", audioUrl: "/audio/divine-comedy/ch-2.mp3" },
      { id: "ch-3", title: "Inferno, Canto III", duration: "16m", audioUrl: "/audio/divine-comedy/ch-3.mp3" },
      { id: "ch-4", title: "Inferno, Canto IV", duration: "17m", audioUrl: "/audio/divine-comedy/ch-4.mp3" },
      { id: "ch-5", title: "Inferno, Canto V", duration: "15m", audioUrl: "/audio/divine-comedy/ch-5.mp3" },
      // More chapters would be added here
    ],
  },
  {
    id: "crime-and-punishment",
    title: "Crime and Punishment",
    author: "Fyodor Dostoevsky",
    description:
      "Crime and Punishment focuses on the mental anguish and moral dilemmas of Rodion Raskolnikov, an impoverished ex-student in Saint Petersburg who formulates a plan to kill an unscrupulous pawnbroker for her money. Before the killing, Raskolnikov believes that with the money he could liberate himself from poverty and go on to perform great deeds.",
    coverUrl: "/crime-and-punishment-cover.png",
    genres: ["Classics", "Psychological", "Literary"],
    duration: "20h 15m",
    pages: 671,
    chapters: [
      { id: "ch-1", title: "Part 1, Chapter 1", duration: "35m", audioUrl: "/audio/crime-and-punishment/ch-1.mp3" },
      { id: "ch-2", title: "Part 1, Chapter 2", duration: "32m", audioUrl: "/audio/crime-and-punishment/ch-2.mp3" },
      { id: "ch-3", title: "Part 1, Chapter 3", duration: "30m", audioUrl: "/audio/crime-and-punishment/ch-3.mp3" },
      { id: "ch-4", title: "Part 1, Chapter 4", duration: "28m", audioUrl: "/audio/crime-and-punishment/ch-4.mp3" },
      { id: "ch-5", title: "Part 1, Chapter 5", duration: "33m", audioUrl: "/audio/crime-and-punishment/ch-5.mp3" },
      // More chapters would be added here
    ],
  },
  {
    id: "brothers-karamazov",
    title: "The Brothers Karamazov",
    author: "Fyodor Dostoevsky",
    description:
      "The Brothers Karamazov is the final novel by the Russian author Fyodor Dostoevsky. Dostoevsky spent nearly two years writing The Brothers Karamazov, which was published as a serial in The Russian Messenger from January 1879 to November 1880.",
    coverUrl: "/brothers-karamazov-cover.png",
    genres: ["Classics", "Philosophical", "Literary"],
    duration: "34h 45m",
    pages: 796,
    chapters: [
      { id: "ch-1", title: "Book 1, Chapter 1", duration: "25m", audioUrl: "/audio/brothers-karamazov/ch-1.mp3" },
      { id: "ch-2", title: "Book 1, Chapter 2", duration: "28m", audioUrl: "/audio/brothers-karamazov/ch-2.mp3" },
      { id: "ch-3", title: "Book 1, Chapter 3", duration: "30m", audioUrl: "/audio/brothers-karamazov/ch-3.mp3" },
      { id: "ch-4", title: "Book 2, Chapter 1", duration: "32m", audioUrl: "/audio/brothers-karamazov/ch-4.mp3" },
      { id: "ch-5", title: "Book 2, Chapter 2", duration: "27m", audioUrl: "/audio/brothers-karamazov/ch-5.mp3" },
      // More chapters would be added here
    ],
  },
  {
    id: "anna-karenina",
    title: "Anna Karenina",
    author: "Leo Tolstoy",
    description:
      "Anna Karenina is a novel by the Russian author Leo Tolstoy, first published in book form in 1878. Widely considered to be one of the greatest works of literature ever written, Tolstoy himself called it his first true novel.",
    coverUrl: "/anna-karenina-cover.png",
    genres: ["Classics", "Romance", "Literary"],
    duration: "35h 30m",
    pages: 964,
    chapters: [
      { id: "ch-1", title: "Part 1, Chapter 1", duration: "18m", audioUrl: "/audio/anna-karenina/ch-1.mp3" },
      { id: "ch-2", title: "Part 1, Chapter 2", duration: "22m", audioUrl: "/audio/anna-karenina/ch-2.mp3" },
      { id: "ch-3", title: "Part 1, Chapter 3", duration: "20m", audioUrl: "/audio/anna-karenina/ch-3.mp3" },
      { id: "ch-4", title: "Part 1, Chapter 4", duration: "19m", audioUrl: "/audio/anna-karenina/ch-4.mp3" },
      { id: "ch-5", title: "Part 1, Chapter 5", duration: "21m", audioUrl: "/audio/anna-karenina/ch-5.mp3" },
      // More chapters would be added here
    ],
  },
  {
    id: "call-of-the-wild",
    title: "The Call of the Wild",
    author: "Jack London",
    description: "A classic adventure novel about a dog named Buck who is stolen from his home and sold into service as a sled dog in Alaska.",
    coverUrl: "/call-of-the-wild-cover.png",
    genres: ["Adventure", "Classic", "Fiction"],
    duration: "3h 45m",
    pages: 232,
    chapters: [
      { id: "1", title: "Chapter 1", duration: "45m", audioUrl: "/audio/call-of-the-wild/chapter1.mp3" },
      { id: "2", title: "Chapter 2", duration: "38m", audioUrl: "/audio/call-of-the-wild/chapter2.mp3" },
      { id: "3", title: "Chapter 3", duration: "42m", audioUrl: "/audio/call-of-the-wild/chapter3.mp3" },
      { id: "4", title: "Chapter 4", duration: "40m", audioUrl: "/audio/call-of-the-wild/chapter4.mp3" },
      { id: "5", title: "Chapter 5", duration: "35m", audioUrl: "/audio/call-of-the-wild/chapter5.mp3" },
    ],
  },
  {
    id: "old-man-and-the-sea",
    title: "The Old Man and the Sea",
    author: "Ernest Hemingway",
    description:
      "The Old Man and the Sea is a novella by the American author Ernest Hemingway. It was first published in 1952 in Esquire magazine and then in book form the same year by Charles Scribner's Sons. It tells the story of an aging Cuban fisherman, Santiago, and his struggle to catch a giant marlin.",
    coverUrl: "/old-man-and-the-sea-cover.png",
    genres: ["Classics", "Adventure", "Literary"],
    duration: "3h 45m",
    pages: 128,
    chapters: [
      { id: "ch-1", title: "The Old Man and the Sea", duration: "35m", audioUrl: "/audio/old-man-and-the-sea/ch-1.mp3" },
      { id: "ch-2", title: "The Boy", duration: "30m", audioUrl: "/audio/old-man-and-the-sea/ch-2.mp3" },
      { id: "ch-3", title: "The Fish", duration: "40m", audioUrl: "/audio/old-man-and-the-sea/ch-3.mp3" },
      { id: "ch-4", title: "The Struggle", duration: "45m", audioUrl: "/audio/old-man-and-the-sea/ch-4.mp3" },
      { id: "ch-5", title: "The Return", duration: "25m", audioUrl: "/audio/old-man-and-the-sea/ch-5.mp3" },
      // More chapters would be added here
    ],
  },
  {
    id: "to-kill-a-mockingbird",
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    description:
      "To Kill a Mockingbird is a novel by the American author Harper Lee. It was published in 1960 and was the author's only published novel until 2015, when Go Set a Watchman was published. The novel is both a young girls' coming-of-age story and a darker drama about the roots and consequences of racism in the Deep South of the United States.",
    coverUrl: "/to-kill-a-mockingbird-cover.png",
    genres: ["Classics", "Historical Fiction", "Coming of Age"],
    duration: "10h 30m",
    pages: 366,
    chapters: [
      { id: "ch-1", title: "Part One: Chapter 1", duration: "30m", audioUrl: "/audio/to-kill-a-mockingbird/ch-1.mp3" },
      { id: "ch-2", title: "Part One: Chapter 2", duration: "28m", audioUrl: "/audio/to-kill-a-mockingbird/ch-2.mp3" },
      { id: "ch-3", title: "Part One: Chapter 3", duration: "32m", audioUrl: "/audio/to-kill-a-mockingbird/ch-3.mp3" },
      { id: "ch-4", title: "Part One: Chapter 4", duration: "27m", audioUrl: "/audio/to-kill-a-mockingbird/ch-4.mp3" },
      { id: "ch-5", title: "Part One: Chapter 5", duration: "29m", audioUrl: "/audio/to-kill-a-mockingbird/ch-5.mp3" },
      // More chapters would be added here
    ],
  },
  {
    id: "les-miserables",
    title: "Les Misérables",
    author: "Victor Hugo",
    description:
      "Les Misérables is a novel by the French author Victor Hugo, first published in 1862. It is considered one of the greatest novels of the 19th century, and is widely regarded as one of the greatest novels of all time. The novel is set in France in the early 19th century and follows the lives of several characters in the years leading up to the June Rebellion of 1832.",
    coverUrl: "/les-miserables-cover.png",
    genres: ["Classics", "Historical Fiction", "Social Commentary"],
    duration: "56h 15m",
    pages: 1462,
    chapters: [
      { id: "ch-1", title: "Part One: Jean Valjean", duration: "1h 5m", audioUrl: "/audio/les-miserables/ch-1.mp3" },
      { id: "ch-2", title: "Part One: Fantine", duration: "1h 10m", audioUrl: "/audio/les-miserables/ch-2.mp3" },
      { id: "ch-3", title: "Part One: Cosette", duration: "1h 15m", audioUrl: "/audio/les-miserables/ch-3.mp3" },
      { id: "ch-4", title: "Part One: The Thénardiers", duration: "1h 5m", audioUrl: "/audio/les-miserables/ch-4.mp3" },
      { id: "ch-5", title: "Part One: The Barricade", duration: "1h 20m", audioUrl: "/audio/les-miserables/ch-5.mp3" },
      // More chapters would be added here
    ],
  },
  {
    id: "meditations",
    title: "Meditations",
    author: "Marcus Aurelius",
    description: "A series of personal writings by Marcus Aurelius, Roman Emperor from 161 to 180 AD, recording his private notes to himself and ideas on Stoic philosophy. The work is considered one of the greatest works of philosophy.",
    coverUrl: "/meditations-cover.png",
    genres: ["Philosophy", "Classics", "Self-Help", "Stoicism"],
    duration: "6h 15m",
    pages: 256,
    chapters: [
      { id: "ch-1", title: "Book I: Debts and Lessons", duration: "35m", audioUrl: "/audio/meditations/ch-1.mp3" },
      { id: "ch-2", title: "Book II: On the River Gran, Among the Quadi", duration: "32m", audioUrl: "/audio/meditations/ch-2.mp3" },
      { id: "ch-3", title: "Book III: In Carnuntum", duration: "30m", audioUrl: "/audio/meditations/ch-3.mp3" },
      { id: "ch-4", title: "Book IV: In Carnuntum", duration: "28m", audioUrl: "/audio/meditations/ch-4.mp3" },
      { id: "ch-5", title: "Book V: At Dawn, When You Have Trouble Getting Out of Bed", duration: "34m", audioUrl: "/audio/meditations/ch-5.mp3" },
    ],
  },
  {
    id: "symposium",
    title: "The Symposium",
    author: "Plato",
    description: "A philosophical text by Plato, dated c. 385–370 BC. It depicts a friendly contest of extemporaneous speeches given by a group of notable men attending a banquet. The men include the philosopher Socrates, the general and political figure Alcibiades, and the comic playwright Aristophanes.",
    coverUrl: "/symposium-cover.png",
    genres: ["Philosophy", "Classics", "Greek Literature", "Dialogue"],
    duration: "4h 45m",
    pages: 131,
    chapters: [
      { id: "ch-1", title: "Introduction", duration: "25m", audioUrl: "/audio/symposium/ch-1.mp3" },
      { id: "ch-2", title: "Phaedrus's Speech", duration: "30m", audioUrl: "/audio/symposium/ch-2.mp3" },
      { id: "ch-3", title: "Pausanias's Speech", duration: "35m", audioUrl: "/audio/symposium/ch-3.mp3" },
      { id: "ch-4", title: "Aristophanes's Speech", duration: "40m", audioUrl: "/audio/symposium/ch-4.mp3" },
      { id: "ch-5", title: "Socrates's Speech", duration: "45m", audioUrl: "/audio/symposium/ch-5.mp3" },
    ],
  },
  {
    id: "metamorphoses",
    title: "Metamorphoses",
    author: "Ovid",
    description: "A narrative poem in fifteen books that describes the creation and history of the world through mythological tales, mostly in the form of stories of transformation. The poem chronicles more than 250 myths from the Greek and Roman traditions.",
    coverUrl: "/metamorphoses-cover.png",
    genres: ["Classics", "Poetry", "Mythology", "Roman Literature"],
    duration: "12h 30m",
    pages: 723,
    chapters: [
      { id: "ch-1", title: "Book I: The Creation and the Four Ages", duration: "45m", audioUrl: "/audio/metamorphoses/ch-1.mp3" },
      { id: "ch-2", title: "Book II: Phaethon", duration: "40m", audioUrl: "/audio/metamorphoses/ch-2.mp3" },
      { id: "ch-3", title: "Book III: Cadmus and the Dragon's Teeth", duration: "38m", audioUrl: "/audio/metamorphoses/ch-3.mp3" },
      { id: "ch-4", title: "Book IV: Pyramus and Thisbe", duration: "35m", audioUrl: "/audio/metamorphoses/ch-4.mp3" },
      { id: "ch-5", title: "Book V: Perseus and Andromeda", duration: "42m", audioUrl: "/audio/metamorphoses/ch-5.mp3" },
    ],
  },
  {
    id: "aeneid",
    title: "The Aeneid",
    author: "Virgil",
    description: "A Latin epic poem written by Virgil between 29 and 19 BC, that tells the legendary story of Aeneas, a Trojan who fled the fall of Troy and traveled to Italy, where he became the ancestor of the Romans.",
    coverUrl: "/aeneid-cover.png",
    genres: ["Classics", "Epic Poetry", "Roman Literature", "Mythology"],
    duration: "11h 45m",
    pages: 442,
    chapters: [
      { id: "ch-1", title: "Book I: A Fateful Haven", duration: "40m", audioUrl: "/audio/aeneid/ch-1.mp3" },
      { id: "ch-2", title: "Book II: The Fall of Troy", duration: "45m", audioUrl: "/audio/aeneid/ch-2.mp3" },
      { id: "ch-3", title: "Book III: Landfalls, Ports of Call", duration: "38m", audioUrl: "/audio/aeneid/ch-3.mp3" },
      { id: "ch-4", title: "Book IV: The Passion of the Queen", duration: "42m", audioUrl: "/audio/aeneid/ch-4.mp3" },
      { id: "ch-5", title: "Book V: Games and a Conflagration", duration: "35m", audioUrl: "/audio/aeneid/ch-5.mp3" },
    ],
  },
  {
    id: "histories",
    title: "The Histories",
    author: "Herodotus",
    description: "Often called 'The Father of History', Herodotus's work is the first major surviving prose work in Western literature. It covers the origins of the Greco-Persian Wars, including the rise of the Persian Empire and the early history of the Greek city-states.",
    coverUrl: "/histories-cover.png",
    genres: ["History", "Classics", "Greek Literature", "Non-Fiction"],
    duration: "24h 15m",
    pages: 716,
    chapters: [
      { id: "ch-1", title: "Book I: Clio", duration: "1h 10m", audioUrl: "/audio/histories/ch-1.mp3" },
      { id: "ch-2", title: "Book II: Euterpe", duration: "1h 15m", audioUrl: "/audio/histories/ch-2.mp3" },
      { id: "ch-3", title: "Book III: Thalia", duration: "1h 5m", audioUrl: "/audio/histories/ch-3.mp3" },
      { id: "ch-4", title: "Book IV: Melpomene", duration: "1h 20m", audioUrl: "/audio/histories/ch-4.mp3" },
      { id: "ch-5", title: "Book V: Terpsichore", duration: "1h 15m", audioUrl: "/audio/histories/ch-5.mp3" },
    ],
  },
  {
    id: "peloponnesian-war",
    title: "History of the Peloponnesian War",
    author: "Thucydides",
    description: "A detailed contemporary account of the Peloponnesian War between Athens and Sparta, written by Thucydides, an Athenian general who served in the war. The work is considered a masterpiece of historical writing.",
    coverUrl: "/peloponnesian-war-cover.png",
    genres: ["History", "Classics", "Greek Literature", "Military History"],
    duration: "28h 30m",
    pages: 648,
    chapters: [
      { id: "ch-1", title: "Book I: The State of Greece from the Earliest Times", duration: "1h 15m", audioUrl: "/audio/peloponnesian-war/ch-1.mp3" },
      { id: "ch-2", title: "Book II: Beginning of the Peloponnesian War", duration: "1h 20m", audioUrl: "/audio/peloponnesian-war/ch-2.mp3" },
      { id: "ch-3", title: "Book III: The Plague of Athens", duration: "1h 10m", audioUrl: "/audio/peloponnesian-war/ch-3.mp3" },
      { id: "ch-4", title: "Book IV: The Revolt of Mytilene", duration: "1h 15m", audioUrl: "/audio/peloponnesian-war/ch-4.mp3" },
      { id: "ch-5", title: "Book V: The Peace of Nicias", duration: "1h 25m", audioUrl: "/audio/peloponnesian-war/ch-5.mp3" },
    ],
  },
  {
    id: "confessions",
    title: "Confessions",
    author: "Saint Augustine",
    description: "An autobiographical work by Saint Augustine of Hippo, consisting of 13 books written in Latin between AD 397 and 400. The work outlines Augustine's sinful youth and his conversion to Christianity.",
    coverUrl: "/confessions-cover.png",
    genres: ["Religion", "Philosophy", "Autobiography", "Classics"],
    duration: "14h 45m",
    pages: 311,
    chapters: [
      { id: "ch-1", title: "Book I: Childhood", duration: "45m", audioUrl: "/audio/confessions/ch-1.mp3" },
      { id: "ch-2", title: "Book II: Adolescence", duration: "40m", audioUrl: "/audio/confessions/ch-2.mp3" },
      { id: "ch-3", title: "Book III: Student at Carthage", duration: "42m", audioUrl: "/audio/confessions/ch-3.mp3" },
      { id: "ch-4", title: "Book IV: Manichaean Period", duration: "38m", audioUrl: "/audio/confessions/ch-4.mp3" },
      { id: "ch-5", title: "Book V: Conversion to Christianity", duration: "45m", audioUrl: "/audio/confessions/ch-5.mp3" },
    ],
  },
  {
    id: "city-of-god",
    title: "The City of God",
    author: "Saint Augustine",
    description: "A book of Christian philosophy written in Latin by Augustine of Hippo in the early 5th century AD. The book was written in response to allegations that Christianity brought about the decline of Rome.",
    coverUrl: "/city-of-god-cover.png",
    genres: ["Religion", "Philosophy", "Theology", "Classics"],
    duration: "32h 15m",
    pages: 1097,
    chapters: [
      { id: "ch-1", title: "Book I: The Pagan Gods and Earthly Happiness", duration: "1h 10m", audioUrl: "/audio/city-of-god/ch-1.mp3" },
      { id: "ch-2", title: "Book II: The Fall of the Roman Gods", duration: "1h 15m", audioUrl: "/audio/city-of-god/ch-2.mp3" },
      { id: "ch-3", title: "Book III: The Fall of the Roman Empire", duration: "1h 20m", audioUrl: "/audio/city-of-god/ch-3.mp3" },
      { id: "ch-4", title: "Book IV: The Two Cities", duration: "1h 15m", audioUrl: "/audio/city-of-god/ch-4.mp3" },
      { id: "ch-5", title: "Book V: The Role of the Christian Emperor", duration: "1h 25m", audioUrl: "/audio/city-of-god/ch-5.mp3" },
    ],
  },
  {
    id: "alice-in-wonderland",
    title: "Alice's Adventures in Wonderland",
    author: "Lewis Carroll",
    description: "A young girl named Alice falls through a rabbit hole into a fantasy world populated by peculiar, anthropomorphic creatures.",
    coverUrl: "/generated-covers/alice-in-wonderland.png",
    genres: ["Classics", "Fantasy", "Children's Literature"],
    duration: "3h",
    pages: 201,
    chapters: [
      { id: "ch-1", title: "Down the Rabbit-Hole", duration: "25m", audioUrl: "/audio/alice-in-wonderland/ch-1.mp3" },
      { id: "ch-2", title: "The Pool of Tears", duration: "22m", audioUrl: "/audio/alice-in-wonderland/ch-2.mp3" },
      { id: "ch-3", title: "A Caucus-Race and a Long Tale", duration: "20m", audioUrl: "/audio/alice-in-wonderland/ch-3.mp3" },
      { id: "ch-4", title: "The Rabbit Sends in a Little Bill", duration: "23m", audioUrl: "/audio/alice-in-wonderland/ch-4.mp3" },
      { id: "ch-5", title: "Advice from a Caterpillar", duration: "21m", audioUrl: "/audio/alice-in-wonderland/ch-5.mp3" },
    ],
  },
  // Additional Classical Works
  {
    id: "nicomachean-ethics",
    title: "Nicomachean Ethics",
    author: "Aristotle",
    description: "Aristotle's examination of the nature of happiness and virtue, and how they relate to each other. The work is considered one of the most important philosophical treatises on ethics.",
    coverUrl: "/nicomachean-ethics-cover.png",
    genres: ["Philosophy", "Classics", "Ethics", "Greek Literature"],
    duration: "10h 30m",
    pages: 329,
    chapters: [
      { id: "ch-1", title: "Book I: The Good for Man", duration: "45m", audioUrl: "/audio/nicomachean-ethics/ch-1.mp3" },
      { id: "ch-2", title: "Book II: Moral Virtue", duration: "42m", audioUrl: "/audio/nicomachean-ethics/ch-2.mp3" },
      { id: "ch-3", title: "Book III: Courage and Temperance", duration: "38m", audioUrl: "/audio/nicomachean-ethics/ch-3.mp3" },
      { id: "ch-4", title: "Book IV: Other Moral Virtues", duration: "40m", audioUrl: "/audio/nicomachean-ethics/ch-4.mp3" },
      { id: "ch-5", title: "Book V: Justice", duration: "44m", audioUrl: "/audio/nicomachean-ethics/ch-5.mp3" },
    ],
  },
  {
    id: "poetics",
    title: "Poetics",
    author: "Aristotle",
    description: "Aristotle's analysis of dramatic theory and the nature of poetry. The work is considered the first systematic treatise on literary theory and has influenced Western literature for centuries.",
    coverUrl: "/poetics-cover.png",
    genres: ["Philosophy", "Classics", "Literary Theory", "Greek Literature"],
    duration: "3h 15m",
    pages: 144,
    chapters: [
      { id: "ch-1", title: "Chapter 1: The Nature of Poetry", duration: "25m", audioUrl: "/audio/poetics/ch-1.mp3" },
      { id: "ch-2", title: "Chapter 2: The Objects of Imitation", duration: "22m", audioUrl: "/audio/poetics/ch-2.mp3" },
      { id: "ch-3", title: "Chapter 3: The Manner of Imitation", duration: "20m", audioUrl: "/audio/poetics/ch-3.mp3" },
      { id: "ch-4", title: "Chapter 4: The Origin and Development of Poetry", duration: "24m", audioUrl: "/audio/poetics/ch-4.mp3" },
      { id: "ch-5", title: "Chapter 5: Comedy and Epic Poetry", duration: "26m", audioUrl: "/audio/poetics/ch-5.mp3" },
    ],
  },
  {
    id: "encheiridion",
    title: "Encheiridion",
    author: "Epictetus",
    description: "A manual of Stoic ethical advice compiled by Arrian, a 2nd-century disciple of the Greek philosopher Epictetus. The work is a concise guide to living a virtuous life.",
    coverUrl: "/encheiridion-cover.png",
    genres: ["Philosophy", "Classics", "Stoicism", "Self-Help"],
    duration: "2h 45m",
    pages: 95,
    chapters: [
      { id: "ch-1", title: "Chapter 1: On What Is in Our Power", duration: "15m", audioUrl: "/audio/encheiridion/ch-1.mp3" },
      { id: "ch-2", title: "Chapter 2: How to Bear Adversity", duration: "18m", audioUrl: "/audio/encheiridion/ch-2.mp3" },
      { id: "ch-3", title: "Chapter 3: On Desires and Aversions", duration: "20m", audioUrl: "/audio/encheiridion/ch-3.mp3" },
      { id: "ch-4", title: "Chapter 4: On the Use of Impressions", duration: "22m", audioUrl: "/audio/encheiridion/ch-4.mp3" },
      { id: "ch-5", title: "Chapter 5: On the Nature of Things", duration: "19m", audioUrl: "/audio/encheiridion/ch-5.mp3" },
    ],
  },
  {
    id: "apology",
    title: "The Apology of Socrates",
    author: "Plato",
    description: "Plato's account of Socrates's speech at his trial in 399 BC, where he was charged with corrupting the youth and impiety. The work is a powerful defense of philosophy and the examined life.",
    coverUrl: "/apology-cover.png",
    genres: ["Philosophy", "Classics", "Greek Literature", "Dialogue"],
    duration: "1h 30m",
    pages: 64,
    chapters: [
      { id: "ch-1", title: "Part 1: Socrates's Defense", duration: "30m", audioUrl: "/audio/apology/ch-1.mp3" },
      { id: "ch-2", title: "Part 2: The Verdict", duration: "25m", audioUrl: "/audio/apology/ch-2.mp3" },
      { id: "ch-3", title: "Part 3: The Sentence", duration: "35m", audioUrl: "/audio/apology/ch-3.mp3" },
    ],
  },
  {
    id: "crito",
    title: "Crito",
    author: "Plato",
    description: "A dialogue between Socrates and his wealthy friend Crito regarding justice, injustice, and the appropriate response to injustice. The work takes place in Socrates's prison cell, where he awaits execution.",
    coverUrl: "/crito-cover.png",
    genres: ["Philosophy", "Classics", "Greek Literature", "Dialogue"],
    duration: "1h 15m",
    pages: 48,
    chapters: [
      { id: "ch-1", title: "The Visit of Crito", duration: "20m", audioUrl: "/audio/crito/ch-1.mp3" },
      { id: "ch-2", title: "The Laws of Athens", duration: "25m", audioUrl: "/audio/crito/ch-2.mp3" },
      { id: "ch-3", title: "The Final Decision", duration: "30m", audioUrl: "/audio/crito/ch-3.mp3" },
    ],
  },
  {
    id: "phaedo",
    title: "Phaedo",
    author: "Plato",
    description: "One of Plato's best-known dialogues, depicting the death of Socrates and his discussion with his friends about the immortality of the soul. The work is a profound meditation on death and the nature of the soul.",
    coverUrl: "/phaedo-cover.png",
    genres: ["Philosophy", "Classics", "Greek Literature", "Dialogue"],
    duration: "3h 45m",
    pages: 156,
    chapters: [
      { id: "ch-1", title: "The Scene", duration: "25m", audioUrl: "/audio/phaedo/ch-1.mp3" },
      { id: "ch-2", title: "The Argument from Opposites", duration: "35m", audioUrl: "/audio/phaedo/ch-2.mp3" },
      { id: "ch-3", title: "The Argument from Recollection", duration: "40m", audioUrl: "/audio/phaedo/ch-3.mp3" },
      { id: "ch-4", title: "The Argument from Affinity", duration: "30m", audioUrl: "/audio/phaedo/ch-4.mp3" },
      { id: "ch-5", title: "The Final Argument", duration: "35m", audioUrl: "/audio/phaedo/ch-5.mp3" },
    ],
  },
  {
    id: "euthyphro",
    title: "Euthyphro",
    author: "Plato",
    description: "A dialogue between Socrates and Euthyphro, a religious expert, discussing the nature of piety. The work is a classic example of Socratic questioning and the search for definitions.",
    coverUrl: "/euthyphro-cover.png",
    genres: ["Philosophy", "Classics", "Greek Literature", "Dialogue"],
    duration: "1h 15m",
    pages: 52,
    chapters: [
      { id: "ch-1", title: "The Meeting", duration: "15m", audioUrl: "/audio/euthyphro/ch-1.mp3" },
      { id: "ch-2", title: "The Definition of Piety", duration: "25m", audioUrl: "/audio/euthyphro/ch-2.mp3" },
      { id: "ch-3", title: "The Euthyphro Dilemma", duration: "35m", audioUrl: "/audio/euthyphro/ch-3.mp3" },
    ],
  },
  {
    id: "meno",
    title: "Meno",
    author: "Plato",
    description: "A dialogue between Socrates and Meno, a young aristocrat, discussing the nature of virtue and whether it can be taught. The work includes the famous 'Meno's paradox' about the possibility of inquiry.",
    coverUrl: "/meno-cover.png",
    genres: ["Philosophy", "Classics", "Greek Literature", "Dialogue"],
    duration: "2h 15m",
    pages: 108,
    chapters: [
      { id: "ch-1", title: "The Question of Virtue", duration: "25m", audioUrl: "/audio/meno/ch-1.mp3" },
      { id: "ch-2", title: "Meno's Paradox", duration: "30m", audioUrl: "/audio/meno/ch-2.mp3" },
      { id: "ch-3", title: "The Theory of Recollection", duration: "35m", audioUrl: "/audio/meno/ch-3.mp3" },
      { id: "ch-4", title: "The Slave Boy Demonstration", duration: "25m", audioUrl: "/audio/meno/ch-4.mp3" },
      { id: "ch-5", title: "Can Virtue Be Taught?", duration: "20m", audioUrl: "/audio/meno/ch-5.mp3" },
    ],
  },
  {
    id: "gorgias",
    title: "Gorgias",
    author: "Plato",
    description: "A dialogue between Socrates and the sophist Gorgias, discussing the nature of rhetoric and its relationship to justice. The work is a powerful critique of sophistry and a defense of philosophy.",
    coverUrl: "/gorgias-cover.png",
    genres: ["Philosophy", "Classics", "Greek Literature", "Dialogue"],
    duration: "4h 30m",
    pages: 216,
    chapters: [
      { id: "ch-1", title: "The Nature of Rhetoric", duration: "45m", audioUrl: "/audio/gorgias/ch-1.mp3" },
      { id: "ch-2", title: "The Power of Rhetoric", duration: "40m", audioUrl: "/audio/gorgias/ch-2.mp3" },
      { id: "ch-3", title: "The True Art of Politics", duration: "50m", audioUrl: "/audio/gorgias/ch-3.mp3" },
      { id: "ch-4", title: "The Life of Pleasure", duration: "45m", audioUrl: "/audio/gorgias/ch-4.mp3" },
      { id: "ch-5", title: "The Final Myth", duration: "30m", audioUrl: "/audio/gorgias/ch-5.mp3" },
    ],
  },
  {
    id: "protagoras",
    title: "Protagoras",
    author: "Plato",
    description: "A dialogue between Socrates and the sophist Protagoras, discussing the nature of virtue and whether it can be taught. The work is a classic example of Socratic questioning and the search for definitions.",
    coverUrl: "/protagoras-cover.png",
    genres: ["Philosophy", "Classics", "Greek Literature", "Dialogue"],
    duration: "3h 45m",
    pages: 180,
    chapters: [
      { id: "ch-1", title: "The Meeting with Hippocrates", duration: "30m", audioUrl: "/audio/protagoras/ch-1.mp3" },
      { id: "ch-2", title: "The Great Speech of Protagoras", duration: "45m", audioUrl: "/audio/protagoras/ch-2.mp3" },
      { id: "ch-3", title: "The Unity of Virtue", duration: "40m", audioUrl: "/audio/protagoras/ch-3.mp3" },
      { id: "ch-4", title: "The Measurement of Pleasure", duration: "35m", audioUrl: "/audio/protagoras/ch-4.mp3" },
      { id: "ch-5", title: "The Final Discussion", duration: "35m", audioUrl: "/audio/protagoras/ch-5.mp3" },
    ],
  },
  // Additional Classical Works (Part 2)
  {
    id: "lives-of-the-caesars",
    title: "The Lives of the Twelve Caesars",
    author: "Suetonius",
    description: "A set of twelve biographies of Julius Caesar and the first 11 emperors of the Roman Empire. The work provides detailed accounts of the public and private lives of these rulers.",
    coverUrl: "/lives-of-the-caesars-cover.png",
    genres: ["History", "Classics", "Biography", "Roman Literature"],
    duration: "15h 30m",
    pages: 416,
    chapters: [
      { id: "ch-1", title: "Julius Caesar", duration: "1h 15m", audioUrl: "/audio/lives-of-the-caesars/ch-1.mp3" },
      { id: "ch-2", title: "Augustus", duration: "1h 20m", audioUrl: "/audio/lives-of-the-caesars/ch-2.mp3" },
      { id: "ch-3", title: "Tiberius", duration: "1h 10m", audioUrl: "/audio/lives-of-the-caesars/ch-3.mp3" },
      { id: "ch-4", title: "Caligula", duration: "1h 5m", audioUrl: "/audio/lives-of-the-caesars/ch-4.mp3" },
      { id: "ch-5", title: "Claudius", duration: "1h 15m", audioUrl: "/audio/lives-of-the-caesars/ch-5.mp3" },
    ],
  },
  {
    id: "parallel-lives",
    title: "Parallel Lives",
    author: "Plutarch",
    description: "A series of biographies of famous Greek and Roman men, arranged in pairs to illuminate their common moral virtues or failings. The work is a masterpiece of biographical writing.",
    coverUrl: "/parallel-lives-cover.png",
    genres: ["History", "Classics", "Biography", "Greek Literature"],
    duration: "45h",
    pages: 1152,
    chapters: [
      { id: "ch-1", title: "Theseus and Romulus", duration: "1h 30m", audioUrl: "/audio/parallel-lives/ch-1.mp3" },
      { id: "ch-2", title: "Lycurgus and Numa", duration: "1h 45m", audioUrl: "/audio/parallel-lives/ch-2.mp3" },
      { id: "ch-3", title: "Solon and Publicola", duration: "1h 35m", audioUrl: "/audio/parallel-lives/ch-3.mp3" },
      { id: "ch-4", title: "Themistocles and Camillus", duration: "1h 40m", audioUrl: "/audio/parallel-lives/ch-4.mp3" },
      { id: "ch-5", title: "Pericles and Fabius Maximus", duration: "1h 50m", audioUrl: "/audio/parallel-lives/ch-5.mp3" },
    ],
  },
  {
    id: "natural-history",
    title: "Natural History",
    author: "Pliny the Elder",
    description: "An encyclopedia of the natural world, covering topics from astronomy to zoology. The work is one of the largest single works to have survived from the Roman Empire.",
    coverUrl: "/natural-history-cover.png",
    genres: ["Science", "Classics", "Encyclopedia", "Roman Literature"],
    duration: "60h",
    pages: 1600,
    chapters: [
      { id: "ch-1", title: "Book I: Preface and Contents", duration: "45m", audioUrl: "/audio/natural-history/ch-1.mp3" },
      { id: "ch-2", title: "Book II: Astronomy", duration: "1h 15m", audioUrl: "/audio/natural-history/ch-2.mp3" },
      { id: "ch-3", title: "Book III: Geography", duration: "1h 30m", audioUrl: "/audio/natural-history/ch-3.mp3" },
      { id: "ch-4", title: "Book IV: Anthropology", duration: "1h 20m", audioUrl: "/audio/natural-history/ch-4.mp3" },
      { id: "ch-5", title: "Book V: Zoology", duration: "1h 25m", audioUrl: "/audio/natural-history/ch-5.mp3" },
    ],
  },
  {
    id: "annals",
    title: "The Annals",
    author: "Tacitus",
    description: "A history of the Roman Empire from the reign of Tiberius to that of Nero. The work is considered one of the greatest historical works of antiquity.",
    coverUrl: "/annals-cover.png",
    genres: ["History", "Classics", "Roman Literature", "Political"],
    duration: "20h 45m",
    pages: 512,
    chapters: [
      { id: "ch-1", title: "Book I: The Death of Augustus", duration: "1h 15m", audioUrl: "/audio/annals/ch-1.mp3" },
      { id: "ch-2", title: "Book II: Germanicus in Germany", duration: "1h 20m", audioUrl: "/audio/annals/ch-2.mp3" },
      { id: "ch-3", title: "Book III: The Trial of Piso", duration: "1h 10m", audioUrl: "/audio/annals/ch-3.mp3" },
      { id: "ch-4", title: "Book IV: The Rise of Sejanus", duration: "1h 25m", audioUrl: "/audio/annals/ch-4.mp3" },
      { id: "ch-5", title: "Book V: The Fall of Sejanus", duration: "1h 15m", audioUrl: "/audio/annals/ch-5.mp3" },
    ],
  },
  {
    id: "germania",
    title: "Germania",
    author: "Tacitus",
    description: "An ethnographic work on the Germanic tribes outside the Roman Empire. The work provides valuable insights into the customs and culture of the ancient Germanic peoples.",
    coverUrl: "/germania-cover.png",
    genres: ["History", "Classics", "Ethnography", "Roman Literature"],
    duration: "2h 15m",
    pages: 96,
    chapters: [
      { id: "ch-1", title: "The Land and Its People", duration: "25m", audioUrl: "/audio/germania/ch-1.mp3" },
      { id: "ch-2", title: "Customs and Institutions", duration: "30m", audioUrl: "/audio/germania/ch-2.mp3" },
      { id: "ch-3", title: "Religion and Superstition", duration: "28m", audioUrl: "/audio/germania/ch-3.mp3" },
      { id: "ch-4", title: "Warfare and Politics", duration: "32m", audioUrl: "/audio/germania/ch-4.mp3" },
      { id: "ch-5", title: "Individual Tribes", duration: "20m", audioUrl: "/audio/germania/ch-5.mp3" },
    ],
  },
  {
    id: "agricola",
    title: "Agricola",
    author: "Tacitus",
    description: "A biography of Tacitus's father-in-law, Gnaeus Julius Agricola, a Roman general who conquered Britain. The work is both a biography and a history of the Roman conquest of Britain.",
    coverUrl: "/agricola-cover.png",
    genres: ["History", "Classics", "Biography", "Roman Literature"],
    duration: "2h 45m",
    pages: 128,
    chapters: [
      { id: "ch-1", title: "Early Life and Career", duration: "25m", audioUrl: "/audio/agricola/ch-1.mp3" },
      { id: "ch-2", title: "Governor of Britain", duration: "35m", audioUrl: "/audio/agricola/ch-2.mp3" },
      { id: "ch-3", title: "The Conquest of Britain", duration: "40m", audioUrl: "/audio/agricola/ch-3.mp3" },
      { id: "ch-4", title: "The Battle of Mons Graupius", duration: "30m", audioUrl: "/audio/agricola/ch-4.mp3" },
      { id: "ch-5", title: "Final Years and Legacy", duration: "35m", audioUrl: "/audio/agricola/ch-5.mp3" },
    ],
  },
  {
    id: "on-the-nature-of-things",
    title: "On the Nature of Things",
    author: "Lucretius",
    description: "A philosophical poem that sets forth the physical theory of the Greek philosopher Epicurus. The work is a masterpiece of Latin poetry and a fundamental text of Epicurean philosophy.",
    coverUrl: "/on-the-nature-of-things-cover.png",
    genres: ["Philosophy", "Classics", "Poetry", "Roman Literature"],
    duration: "8h 15m",
    pages: 384,
    chapters: [
      { id: "ch-1", title: "Book I: Matter and Space", duration: "45m", audioUrl: "/audio/on-the-nature-of-things/ch-1.mp3" },
      { id: "ch-2", title: "Book II: The Nature of Atoms", duration: "50m", audioUrl: "/audio/on-the-nature-of-things/ch-2.mp3" },
      { id: "ch-3", title: "Book III: The Nature of the Mind", duration: "55m", audioUrl: "/audio/on-the-nature-of-things/ch-3.mp3" },
      { id: "ch-4", title: "Book IV: Sensation and Thought", duration: "48m", audioUrl: "/audio/on-the-nature-of-things/ch-4.mp3" },
      { id: "ch-5", title: "Book V: The World and Its Development", duration: "52m", audioUrl: "/audio/on-the-nature-of-things/ch-5.mp3" },
    ],
  },
  {
    id: "on-duties",
    title: "On Duties",
    author: "Cicero",
    description: "A treatise on moral philosophy, written as a letter to his son. The work discusses the nature of moral duty and how to live a virtuous life.",
    coverUrl: "/on-duties-cover.png",
    genres: ["Philosophy", "Classics", "Ethics", "Roman Literature"],
    duration: "6h 30m",
    pages: 288,
    chapters: [
      { id: "ch-1", title: "Book I: The Honorable", duration: "1h 15m", audioUrl: "/audio/on-duties/ch-1.mp3" },
      { id: "ch-2", title: "Book II: The Useful", duration: "1h 20m", audioUrl: "/audio/on-duties/ch-2.mp3" },
      { id: "ch-3", title: "Book III: The Conflict Between the Honorable and the Useful", duration: "1h 25m", audioUrl: "/audio/on-duties/ch-3.mp3" },
    ],
  },
  {
    id: "on-the-orator",
    title: "On the Orator",
    author: "Cicero",
    description: "A dialogue on the ideal orator and the art of rhetoric. The work is considered one of the most important treatises on rhetoric ever written.",
    coverUrl: "/on-the-orator-cover.png",
    genres: ["Philosophy", "Classics", "Rhetoric", "Roman Literature"],
    duration: "12h 45m",
    pages: 576,
    chapters: [
      { id: "ch-1", title: "Book I: The Nature of Eloquence", duration: "1h 30m", audioUrl: "/audio/on-the-orator/ch-1.mp3" },
      { id: "ch-2", title: "Book II: The Education of the Orator", duration: "1h 45m", audioUrl: "/audio/on-the-orator/ch-2.mp3" },
      { id: "ch-3", title: "Book III: The Style of the Orator", duration: "1h 40m", audioUrl: "/audio/on-the-orator/ch-3.mp3" },
    ],
  },
  {
    id: "on-the-nature-of-the-gods",
    title: "On the Nature of the Gods",
    author: "Cicero",
    description: "A philosophical dialogue examining the nature of the gods and the existence of divine providence. The work presents the views of different philosophical schools on theology.",
    coverUrl: "/on-the-nature-of-the-gods-cover.png",
    genres: ["Philosophy", "Classics", "Theology", "Roman Literature"],
    duration: "8h 15m",
    pages: 384,
    chapters: [
      { id: "ch-1", title: "Book I: The Epicurean View", duration: "1h 15m", audioUrl: "/audio/on-the-nature-of-the-gods/ch-1.mp3" },
      { id: "ch-2", title: "Book II: The Stoic View", duration: "1h 30m", audioUrl: "/audio/on-the-nature-of-the-gods/ch-2.mp3" },
      { id: "ch-3", title: "Book III: The Academic View", duration: "1h 20m", audioUrl: "/audio/on-the-nature-of-the-gods/ch-3.mp3" },
    ],
  },
  // Additional Classical Works (Part 3)
  {
    id: "theogony",
    title: "Theogony",
    author: "Hesiod",
    description: "A poem describing the origins and genealogies of the Greek gods. The work is one of the most important sources for Greek mythology and the earliest known attempt to systematize the Greek pantheon.",
    coverUrl: "/theogony-cover.png",
    genres: ["Mythology", "Classics", "Poetry", "Greek Literature"],
    duration: "2h 30m",
    pages: 128,
    chapters: [
      { id: "ch-1", title: "The Muses and Their Gifts", duration: "25m", audioUrl: "/audio/theogony/ch-1.mp3" },
      { id: "ch-2", title: "The First Gods", duration: "30m", audioUrl: "/audio/theogony/ch-2.mp3" },
      { id: "ch-3", title: "The Titans", duration: "35m", audioUrl: "/audio/theogony/ch-3.mp3" },
      { id: "ch-4", title: "The Olympians", duration: "30m", audioUrl: "/audio/theogony/ch-4.mp3" },
      { id: "ch-5", title: "The Heroes", duration: "30m", audioUrl: "/audio/theogony/ch-5.mp3" },
    ],
  },
  {
    id: "works-and-days",
    title: "Works and Days",
    author: "Hesiod",
    description: "A didactic poem offering advice on farming and moral living. The work combines practical agricultural advice with moral and religious instruction.",
    coverUrl: "/works-and-days-cover.png",
    genres: ["Classics", "Poetry", "Agriculture", "Greek Literature"],
    duration: "2h 15m",
    pages: 96,
    chapters: [
      { id: "ch-1", title: "The Two Strifes", duration: "20m", audioUrl: "/audio/works-and-days/ch-1.mp3" },
      { id: "ch-2", title: "The Myth of the Ages", duration: "25m", audioUrl: "/audio/works-and-days/ch-2.mp3" },
      { id: "ch-3", title: "Farming Calendar", duration: "30m", audioUrl: "/audio/works-and-days/ch-3.mp3" },
      { id: "ch-4", title: "Seafaring", duration: "20m", audioUrl: "/audio/works-and-days/ch-4.mp3" },
      { id: "ch-5", title: "Days of the Month", duration: "40m", audioUrl: "/audio/works-and-days/ch-5.mp3" },
    ],
  },
  {
    id: "homeric-hymns",
    title: "Homeric Hymns",
    author: "Anonymous",
    description: "A collection of thirty-three anonymous ancient Greek hymns celebrating individual gods. The hymns are called 'Homeric' because they are written in the same style as the Iliad and Odyssey.",
    coverUrl: "/homeric-hymns-cover.png",
    genres: ["Mythology", "Classics", "Poetry", "Greek Literature"],
    duration: "3h 45m",
    pages: 192,
    chapters: [
      { id: "ch-1", title: "To Demeter", duration: "25m", audioUrl: "/audio/homeric-hymns/ch-1.mp3" },
      { id: "ch-2", title: "To Apollo", duration: "30m", audioUrl: "/audio/homeric-hymns/ch-2.mp3" },
      { id: "ch-3", title: "To Hermes", duration: "35m", audioUrl: "/audio/homeric-hymns/ch-3.mp3" },
      { id: "ch-4", title: "To Aphrodite", duration: "25m", audioUrl: "/audio/homeric-hymns/ch-4.mp3" },
      { id: "ch-5", title: "To Dionysus", duration: "30m", audioUrl: "/audio/homeric-hymns/ch-5.mp3" },
    ],
  },
  {
    id: "didache",
    title: "The Didache",
    author: "Anonymous",
    description: "An early Christian treatise containing instructions for Christian communities. The work is considered one of the earliest Christian documents outside the New Testament.",
    coverUrl: "/didache-cover.png",
    genres: ["Religion", "Classics", "Christianity", "Early Christian Literature"],
    duration: "1h 15m",
    pages: 64,
    chapters: [
      { id: "ch-1", title: "The Two Ways", duration: "15m", audioUrl: "/audio/didache/ch-1.mp3" },
      { id: "ch-2", title: "The Second Commandment", duration: "10m", audioUrl: "/audio/didache/ch-2.mp3" },
      { id: "ch-3", title: "Baptism", duration: "15m", audioUrl: "/audio/didache/ch-3.mp3" },
      { id: "ch-4", title: "The Eucharist", duration: "15m", audioUrl: "/audio/didache/ch-4.mp3" },
      { id: "ch-5", title: "Church Organization", duration: "20m", audioUrl: "/audio/didache/ch-5.mp3" },
    ],
  },
  {
    id: "shepherd-of-hermas",
    title: "The Shepherd of Hermas",
    author: "Hermas",
    description: "An early Christian literary work consisting of visions, mandates, and parables. The work was highly regarded in early Christianity and was considered canonical by some early Church Fathers.",
    coverUrl: "/shepherd-of-hermas-cover.png",
    genres: ["Religion", "Classics", "Christianity", "Early Christian Literature"],
    duration: "4h 30m",
    pages: 256,
    chapters: [
      { id: "ch-1", title: "Visions", duration: "45m", audioUrl: "/audio/shepherd-of-hermas/ch-1.mp3" },
      { id: "ch-2", title: "Mandates", duration: "1h", audioUrl: "/audio/shepherd-of-hermas/ch-2.mp3" },
      { id: "ch-3", title: "Parables", duration: "1h 15m", audioUrl: "/audio/shepherd-of-hermas/ch-3.mp3" },
      { id: "ch-4", title: "The Building of the Tower", duration: "45m", audioUrl: "/audio/shepherd-of-hermas/ch-4.mp3" },
      { id: "ch-5", title: "The Twelve Mountains", duration: "45m", audioUrl: "/audio/shepherd-of-hermas/ch-5.mp3" },
    ],
  },
  {
    id: "first-clement",
    title: "First Epistle of Clement",
    author: "Clement of Rome",
    description: "A letter addressed to the Christian Church in Corinth. The work is one of the earliest Christian documents outside the New Testament and provides insight into early Church organization and practice.",
    coverUrl: "/first-clement-cover.png",
    genres: ["Religion", "Classics", "Christianity", "Early Christian Literature"],
    duration: "2h",
    pages: 128,
    chapters: [
      { id: "ch-1", title: "Greeting and Thanksgiving", duration: "15m", audioUrl: "/audio/first-clement/ch-1.mp3" },
      { id: "ch-2", title: "The Need for Humility", duration: "20m", audioUrl: "/audio/first-clement/ch-2.mp3" },
      { id: "ch-3", title: "Examples of Humility", duration: "25m", audioUrl: "/audio/first-clement/ch-3.mp3" },
      { id: "ch-4", title: "The Need for Peace and Harmony", duration: "30m", audioUrl: "/audio/first-clement/ch-4.mp3" },
      { id: "ch-5", title: "Conclusion and Benediction", duration: "30m", audioUrl: "/audio/first-clement/ch-5.mp3" },
    ],
  },
  {
    id: "epistle-of-barnabas",
    title: "Epistle of Barnabas",
    author: "Barnabas",
    description: "An early Christian epistle containing moral and allegorical interpretations of the Old Testament. The work was highly regarded in early Christianity and was considered canonical by some early Church Fathers.",
    coverUrl: "/epistle-of-barnabas-cover.png",
    genres: ["Religion", "Classics", "Christianity", "Early Christian Literature"],
    duration: "2h 15m",
    pages: 96,
    chapters: [
      { id: "ch-1", title: "Introduction", duration: "15m", audioUrl: "/audio/epistle-of-barnabas/ch-1.mp3" },
      { id: "ch-2", title: "The Old Covenant", duration: "25m", audioUrl: "/audio/epistle-of-barnabas/ch-2.mp3" },
      { id: "ch-3", title: "The New Covenant", duration: "30m", audioUrl: "/audio/epistle-of-barnabas/ch-3.mp3" },
      { id: "ch-4", title: "The Way of Light", duration: "25m", audioUrl: "/audio/epistle-of-barnabas/ch-4.mp3" },
      { id: "ch-5", title: "The Way of Darkness", duration: "40m", audioUrl: "/audio/epistle-of-barnabas/ch-5.mp3" },
    ],
  },
  {
    id: "martyrdom-of-polycarp",
    title: "The Martyrdom of Polycarp",
    author: "Anonymous",
    description: "An early Christian account of the martyrdom of Polycarp, Bishop of Smyrna. The work is one of the earliest accounts of Christian martyrdom and provides insight into early Christian attitudes toward persecution.",
    coverUrl: "/martyrdom-of-polycarp-cover.png",
    genres: ["Religion", "Classics", "Christianity", "Early Christian Literature"],
    duration: "1h 30m",
    pages: 64,
    chapters: [
      { id: "ch-1", title: "Introduction", duration: "10m", audioUrl: "/audio/martyrdom-of-polycarp/ch-1.mp3" },
      { id: "ch-2", title: "The Arrest", duration: "15m", audioUrl: "/audio/martyrdom-of-polycarp/ch-2.mp3" },
      { id: "ch-3", title: "The Trial", duration: "20m", audioUrl: "/audio/martyrdom-of-polycarp/ch-3.mp3" },
      { id: "ch-4", title: "The Execution", duration: "25m", audioUrl: "/audio/martyrdom-of-polycarp/ch-4.mp3" },
      { id: "ch-5", title: "The Aftermath", duration: "20m", audioUrl: "/audio/martyrdom-of-polycarp/ch-5.mp3" },
    ],
  },
  {
    id: "apology-of-justin-martyr",
    title: "First Apology of Justin Martyr",
    author: "Justin Martyr",
    description: "An early Christian apologetic work addressed to the Roman Emperor Antoninus Pius. The work defends Christianity against pagan accusations and explains Christian beliefs and practices.",
    coverUrl: "/apology-of-justin-martyr-cover.png",
    genres: ["Religion", "Classics", "Christianity", "Early Christian Literature"],
    duration: "3h",
    pages: 160,
    chapters: [
      { id: "ch-1", title: "Introduction", duration: "20m", audioUrl: "/audio/apology-of-justin-martyr/ch-1.mp3" },
      { id: "ch-2", title: "Christian Worship", duration: "35m", audioUrl: "/audio/apology-of-justin-martyr/ch-2.mp3" },
      { id: "ch-3", title: "Christian Morality", duration: "40m", audioUrl: "/audio/apology-of-justin-martyr/ch-3.mp3" },
      { id: "ch-4", title: "Christian Prophecy", duration: "35m", audioUrl: "/audio/apology-of-justin-martyr/ch-4.mp3" },
      { id: "ch-5", title: "Conclusion", duration: "30m", audioUrl: "/audio/apology-of-justin-martyr/ch-5.mp3" },
    ],
  },
  {
    id: "dialogue-with-trypho",
    title: "Dialogue with Trypho",
    author: "Justin Martyr",
    description: "An early Christian apologetic work in the form of a dialogue between Justin and a Jewish man named Trypho. The work discusses the relationship between Christianity and Judaism.",
    coverUrl: "/dialogue-with-trypho-cover.png",
    genres: ["Religion", "Classics", "Christianity", "Early Christian Literature"],
    duration: "5h 15m",
    pages: 288,
    chapters: [
      { id: "ch-1", title: "The Meeting", duration: "30m", audioUrl: "/audio/dialogue-with-trypho/ch-1.mp3" },
      { id: "ch-2", title: "The Law", duration: "45m", audioUrl: "/audio/dialogue-with-trypho/ch-2.mp3" },
      { id: "ch-3", title: "The Messiah", duration: "1h", audioUrl: "/audio/dialogue-with-trypho/ch-3.mp3" },
      { id: "ch-4", title: "The New Covenant", duration: "1h 15m", audioUrl: "/audio/dialogue-with-trypho/ch-4.mp3" },
      { id: "ch-5", title: "Conclusion", duration: "45m", audioUrl: "/audio/dialogue-with-trypho/ch-5.mp3" },
    ],
  },
  // Additional Classical Works (Part 4)
  {
    id: "second-clement",
    title: "Second Epistle of Clement",
    author: "Clement of Rome",
    description: "An early Christian homily, traditionally attributed to Clement of Rome. The work focuses on moral instruction and the importance of repentance.",
    coverUrl: "/second-clement-cover.png",
    genres: ["Religion", "Classics", "Christianity", "Early Christian Literature"],
    duration: "1h 30m",
    pages: 64,
    chapters: [
      { id: "ch-1", title: "Introduction", duration: "15m", audioUrl: "/audio/second-clement/ch-1.mp3" },
      { id: "ch-2", title: "The Call to Repentance", duration: "20m", audioUrl: "/audio/second-clement/ch-2.mp3" },
      { id: "ch-3", title: "The Importance of Good Works", duration: "25m", audioUrl: "/audio/second-clement/ch-3.mp3" },
      { id: "ch-4", title: "The Resurrection", duration: "15m", audioUrl: "/audio/second-clement/ch-4.mp3" },
      { id: "ch-5", title: "Conclusion", duration: "15m", audioUrl: "/audio/second-clement/ch-5.mp3" },
    ],
  },
  {
    id: "epistle-to-diopnetus",
    title: "Epistle to Diognetus",
    author: "Anonymous",
    description: "An early Christian apologetic work explaining the nature of Christianity to a pagan audience. The work is notable for its elegant style and clear presentation of Christian beliefs.",
    coverUrl: "/epistle-to-diognetus-cover.png",
    genres: ["Religion", "Classics", "Christianity", "Early Christian Literature"],
    duration: "1h 15m",
    pages: 48,
    chapters: [
      { id: "ch-1", title: "Introduction", duration: "10m", audioUrl: "/audio/epistle-to-diognetus/ch-1.mp3" },
      { id: "ch-2", title: "The Christian Way of Life", duration: "15m", audioUrl: "/audio/epistle-to-diognetus/ch-2.mp3" },
      { id: "ch-3", title: "The Christian Faith", duration: "20m", audioUrl: "/audio/epistle-to-diognetus/ch-3.mp3" },
      { id: "ch-4", title: "The Christian Hope", duration: "15m", audioUrl: "/audio/epistle-to-diognetus/ch-4.mp3" },
      { id: "ch-5", title: "Conclusion", duration: "15m", audioUrl: "/audio/epistle-to-diognetus/ch-5.mp3" },
    ],
  },
  {
    id: "fragments-of-papias",
    title: "Fragments of Papias",
    author: "Papias of Hierapolis",
    description: "Surviving fragments of a work by Papias of Hierapolis, an early Christian bishop. The work contains valuable information about the origins of the Gospels and early Christian traditions.",
    coverUrl: "/fragments-of-papias-cover.png",
    genres: ["Religion", "Classics", "Christianity", "Early Christian Literature"],
    duration: "45m",
    pages: 32,
    chapters: [
      { id: "ch-1", title: "Introduction", duration: "5m", audioUrl: "/audio/fragments-of-papias/ch-1.mp3" },
      { id: "ch-2", title: "On the Gospels", duration: "10m", audioUrl: "/audio/fragments-of-papias/ch-2.mp3" },
      { id: "ch-3", title: "On the Apostles", duration: "15m", audioUrl: "/audio/fragments-of-papias/ch-3.mp3" },
      { id: "ch-4", title: "On Early Traditions", duration: "10m", audioUrl: "/audio/fragments-of-papias/ch-4.mp3" },
      { id: "ch-5", title: "Conclusion", duration: "5m", audioUrl: "/audio/fragments-of-papias/ch-5.mp3" },
    ],
  },
  {
    id: "apostolic-constitutions",
    title: "Apostolic Constitutions",
    author: "Anonymous",
    description: "A collection of early Christian ecclesiastical regulations and liturgical practices. The work provides valuable insight into early Christian worship and church organization.",
    coverUrl: "/apostolic-constitutions-cover.png",
    genres: ["Religion", "Classics", "Christianity", "Early Christian Literature"],
    duration: "8h",
    pages: 384,
    chapters: [
      { id: "ch-1", title: "Book I: On the Laity", duration: "1h", audioUrl: "/audio/apostolic-constitutions/ch-1.mp3" },
      { id: "ch-2", title: "Book II: On Bishops and Deacons", duration: "1h 30m", audioUrl: "/audio/apostolic-constitutions/ch-2.mp3" },
      { id: "ch-3", title: "Book III: On Widows", duration: "1h 15m", audioUrl: "/audio/apostolic-constitutions/ch-3.mp3" },
      { id: "ch-4", title: "Book IV: On Orphans", duration: "1h 20m", audioUrl: "/audio/apostolic-constitutions/ch-4.mp3" },
      { id: "ch-5", title: "Book V: On Martyrs", duration: "1h 15m", audioUrl: "/audio/apostolic-constitutions/ch-5.mp3" },
    ],
  },
  {
    id: "apostolic-tradition",
    title: "Apostolic Tradition",
    author: "Hippolytus of Rome",
    description: "An early Christian work describing the practices and customs of the Roman Church. The work is particularly valuable for its information about early Christian liturgy and church organization.",
    coverUrl: "/apostolic-tradition-cover.png",
    genres: ["Religion", "Classics", "Christianity", "Early Christian Literature"],
    duration: "2h 30m",
    pages: 128,
    chapters: [
      { id: "ch-1", title: "On Bishops", duration: "25m", audioUrl: "/audio/apostolic-tradition/ch-1.mp3" },
      { id: "ch-2", title: "On Presbyters", duration: "20m", audioUrl: "/audio/apostolic-tradition/ch-2.mp3" },
      { id: "ch-3", title: "On Deacons", duration: "25m", audioUrl: "/audio/apostolic-tradition/ch-3.mp3" },
      { id: "ch-4", title: "On Confessors", duration: "30m", audioUrl: "/audio/apostolic-tradition/ch-4.mp3" },
      { id: "ch-5", title: "On Widows", duration: "30m", audioUrl: "/audio/apostolic-tradition/ch-5.mp3" },
    ],
  },
  {
    id: "on-the-unity-of-the-church",
    title: "On the Unity of the Church",
    author: "Cyprian of Carthage",
    description: "A treatise on the importance of unity in the Christian Church. The work was written during a period of schism in the Church and emphasizes the necessity of maintaining communion with the bishop.",
    coverUrl: "/on-the-unity-of-the-church-cover.png",
    genres: ["Religion", "Classics", "Christianity", "Early Christian Literature"],
    duration: "2h 15m",
    pages: 96,
    chapters: [
      { id: "ch-1", title: "Introduction", duration: "15m", audioUrl: "/audio/on-the-unity-of-the-church/ch-1.mp3" },
      { id: "ch-2", title: "The Unity of the Church", duration: "30m", audioUrl: "/audio/on-the-unity-of-the-church/ch-2.mp3" },
      { id: "ch-3", title: "The Authority of the Bishop", duration: "30m", audioUrl: "/audio/on-the-unity-of-the-church/ch-3.mp3" },
      { id: "ch-4", title: "The Danger of Schism", duration: "30m", audioUrl: "/audio/on-the-unity-of-the-church/ch-4.mp3" },
      { id: "ch-5", title: "Conclusion", duration: "30m", audioUrl: "/audio/on-the-unity-of-the-church/ch-5.mp3" },
    ],
  },
  {
    id: "on-the-lapsed",
    title: "On the Lapsed",
    author: "Cyprian of Carthage",
    description: "A treatise addressing the problem of Christians who had renounced their faith during persecution. The work discusses the proper treatment of those who had lapsed and wished to return to the Church.",
    coverUrl: "/on-the-lapsed-cover.png",
    genres: ["Religion", "Classics", "Christianity", "Early Christian Literature"],
    duration: "2h 45m",
    pages: 128,
    chapters: [
      { id: "ch-1", title: "Introduction", duration: "20m", audioUrl: "/audio/on-the-lapsed/ch-1.mp3" },
      { id: "ch-2", title: "The Nature of Apostasy", duration: "35m", audioUrl: "/audio/on-the-lapsed/ch-2.mp3" },
      { id: "ch-3", title: "The Need for Repentance", duration: "35m", audioUrl: "/audio/on-the-lapsed/ch-3.mp3" },
      { id: "ch-4", title: "The Process of Reconciliation", duration: "35m", audioUrl: "/audio/on-the-lapsed/ch-4.mp3" },
      { id: "ch-5", title: "Conclusion", duration: "40m", audioUrl: "/audio/on-the-lapsed/ch-5.mp3" },
    ],
  },
  {
    id: "on-the-dress-of-virgins",
    title: "On the Dress of Virgins",
    author: "Cyprian of Carthage",
    description: "A treatise on the proper conduct and appearance of Christian virgins. The work emphasizes the importance of modesty and spiritual purity.",
    coverUrl: "/on-the-dress-of-virgins-cover.png",
    genres: ["Religion", "Classics", "Christianity", "Early Christian Literature"],
    duration: "1h 45m",
    pages: 80,
    chapters: [
      { id: "ch-1", title: "Introduction", duration: "15m", audioUrl: "/audio/on-the-dress-of-virgins/ch-1.mp3" },
      { id: "ch-2", title: "The Virtue of Modesty", duration: "25m", audioUrl: "/audio/on-the-dress-of-virgins/ch-2.mp3" },
      { id: "ch-3", title: "The Dangers of Vanity", duration: "25m", audioUrl: "/audio/on-the-dress-of-virgins/ch-3.mp3" },
      { id: "ch-4", title: "The Beauty of Virtue", duration: "20m", audioUrl: "/audio/on-the-dress-of-virgins/ch-4.mp3" },
      { id: "ch-5", title: "Conclusion", duration: "20m", audioUrl: "/audio/on-the-dress-of-virgins/ch-5.mp3" },
    ],
  },
  {
    id: "on-the-good-of-patience",
    title: "On the Good of Patience",
    author: "Cyprian of Carthage",
    description: "A treatise on the virtue of patience and its importance in the Christian life. The work uses examples from Scripture to illustrate the value of patience in various circumstances.",
    coverUrl: "/on-the-good-of-patience-cover.png",
    genres: ["Religion", "Classics", "Christianity", "Early Christian Literature"],
    duration: "1h 30m",
    pages: 64,
    chapters: [
      { id: "ch-1", title: "Introduction", duration: "10m", audioUrl: "/audio/on-the-good-of-patience/ch-1.mp3" },
      { id: "ch-2", title: "The Nature of Patience", duration: "20m", audioUrl: "/audio/on-the-good-of-patience/ch-2.mp3" },
      { id: "ch-3", title: "Examples from Scripture", duration: "25m", audioUrl: "/audio/on-the-good-of-patience/ch-3.mp3" },
      { id: "ch-4", title: "The Benefits of Patience", duration: "20m", audioUrl: "/audio/on-the-good-of-patience/ch-4.mp3" },
      { id: "ch-5", title: "Conclusion", duration: "15m", audioUrl: "/audio/on-the-good-of-patience/ch-5.mp3" },
    ],
  },
  {
    id: "on-the-value-of-martyrdom",
    title: "On the Value of Martyrdom",
    author: "Cyprian of Carthage",
    description: "A treatise encouraging Christians to remain faithful during persecution. The work emphasizes the spiritual benefits of martyrdom and the importance of maintaining one's faith under pressure.",
    coverUrl: "/on-the-value-of-martyrdom-cover.png",
    genres: ["Religion", "Classics", "Christianity", "Early Christian Literature"],
    duration: "2h",
    pages: 96,
    chapters: [
      { id: "ch-1", title: "Introduction", duration: "15m", audioUrl: "/audio/on-the-value-of-martyrdom/ch-1.mp3" },
      { id: "ch-2", title: "The Glory of Martyrdom", duration: "25m", audioUrl: "/audio/on-the-value-of-martyrdom/ch-2.mp3" },
      { id: "ch-3", title: "The Example of the Martyrs", duration: "30m", audioUrl: "/audio/on-the-value-of-martyrdom/ch-3.mp3" },
      { id: "ch-4", title: "The Reward of Faithfulness", duration: "25m", audioUrl: "/audio/on-the-value-of-martyrdom/ch-4.mp3" },
      { id: "ch-5", title: "Conclusion", duration: "25m", audioUrl: "/audio/on-the-value-of-martyrdom/ch-5.mp3" },
    ],
  },
]

export function getAllBooks(): Book[] {
  return books
}

export function getBookById(id: string): Book | undefined {
  return books.find((book) => book.id === id)
}

// Get the currently playing book (for demo purposes, returns the demo book)
export function getCurrentBook(): Book | null {
  // Get all books with proper cover art (not placeholder.svg)
  const booksWithCoverArt = books.filter(book => !book.coverUrl.includes('placeholder.svg'))
  
  // If we have books with cover art, randomly select one
  if (booksWithCoverArt.length > 0) {
    const randomIndex = Math.floor(Math.random() * booksWithCoverArt.length)
    return {
      ...booksWithCoverArt[randomIndex],
      progress: 0,
      isFavorite: false
    }
  }
  
  // Fallback to a default book if no books with cover art are found
  return {
    id: "call-of-the-wild",
    title: "The Call of the Wild",
    author: "Jack London",
    description: "A classic adventure novel about a dog named Buck who is stolen from his home and sold into service as a sled dog in Alaska.",
    coverUrl: "/call-of-the-wild-cover.png",
    duration: "3h 45m",
    genres: ["Adventure", "Classic", "Fiction"],
    progress: 0,
    isFavorite: false,
    pages: 232,
    chapters: [
      { id: "1", title: "Chapter 1", duration: "45m", audioUrl: "/audio/call-of-the-wild/chapter1.mp3" },
      { id: "2", title: "Chapter 2", duration: "38m", audioUrl: "/audio/call-of-the-wild/chapter2.mp3" },
      { id: "3", title: "Chapter 3", duration: "42m", audioUrl: "/audio/call-of-the-wild/chapter3.mp3" },
      { id: "4", title: "Chapter 4", duration: "40m", audioUrl: "/audio/call-of-the-wild/chapter4.mp3" },
      { id: "5", title: "Chapter 5", duration: "35m", audioUrl: "/audio/call-of-the-wild/chapter5.mp3" },
    ]
  }
}
